# 구 day0.json → 새 day1 (바 2부) 변환
# 원본: Assets/StreamingAssets/day0.json + day0_crafts.json (구 노드그래프 → 신 씬-스텝)
# 구 씬: day0_chris (단일 씬, 크리스의 드라이 마티니 강습) / choices 노드 없음

CONFLICTS = [
    "비선형 점프(재시도 루프): d0c_react_normal_006 및 d0c_react_bad_009가 start_craft(day0_chris_order1)로 재진입하는 루프 구조. 신 구조는 선형이므로 'grade < good' 게이트로 재도전 1회(order/craft/serve 재배치)로 평탄화. 2회째 실패 시의 무한 루프는 재현 불가 — 재도전 후 grade 재평가로 게이트가 재적용되는지 엔진 확인 필요.",
    "도달 불가 분기 제외: d0c_react_bad_001~009(재료 낭비 질책 라인)는 구 crafts 평가 규칙상 도달 불가(어떤 rule도 result 'bad'를 내지 않고, bad_nm_fail 리액션도 d0c_react_normal_001 대사를 참조). 변환에서 제외함.",
    "컷씬 id 확인 필요: 'Intro_lab_Sprite' (day0_chris_x1 start_cutscene → timeline 스텝). 신 cutscenes 데이터에 동일 id 존재 여부 확인 필요.",
    "제조 완료 컷씬 미이식: day0_crafts.json cutscenes.finish.default = 'day1_finish_default'. 신 스텝 구조에 대응 필드가 없어 craft 스텝 note로만 기록.",
    "when DSL 확장 사용: 판정 3분기(perfect/good/normal)를 표현하기 위해 'grade >= perfect', 'grade >= good && grade < perfect' 사용. 예시 DSL에는 good 비교만 등장 — perfect 등급 토큰 지원 여부 확인 필요.",
    "reactions의 skill 보상(perfect +3, good +2) 및 payment 설정은 effects DSL(flag/affinity/money/quest)로 표현 불가 — 미이식. affinity(perfect +5, good +1)만 affinity.chris로 이식.",
    "expression 'fail' (day0_chris_x7, x14, d0c_react_normal_001): 신 표정 데이터에 'fail' 존재 여부 확인 필요 (참고 데이터에서는 default/success/joy/serious/drunk만 확인됨).",
    "해금일 충돌 의심: 구 day0 튜토리얼 칵테일은 dry_martini이나, 신엔진 참고 데이터의 d1_tutorial은 gin_tonic 사용. day1 시점 dry_martini 해금 여부 확인 필요.",
    "텍스트 마크업 태그(<order>/<name>/<world>)는 ko/en 모두 원형 유지 — 신 text_styles 호환 확인 필요.",
    "구 customer_enter의 enter_effect 'silhouette_reveal', sfx_mode 'default_only'는 신 enter 스텝에 대응 필드 없음 — note로만 기록.",
    "day0.json에 choices[] 노드가 전혀 없어 CHOICES는 빈 리스트. 분기 전용 manual 씬도 불필요.",
]

# (id, day, phase, seq, trigger, when, title)  — 7필드
SCENES = [
    ("d1_tutorial_chris", 1, "bar", 1, "auto", "", "튜토리얼 — 크리스의 드라이 마티니 강습 (구 day0_chris)"),
    ("d1_tutorial_wrap",  1, "bar", 2, "auto", "", "튜토리얼 마무리 — 애매한 주문 조언 + '보스' 호칭 (구 d0c_end)"),
]

# (scene_id, seq, type, actor, arg, text_ko, text_en, when, effects, note)  — 10필드
STEPS = [
    # ---------- d1_tutorial_chris : 인트로 컷씬 ~ 제조/판정 ----------
    ("d1_tutorial_chris", 1,  "timeline", "", "Intro_lab_Sprite", "", "", "", "", "컷씬 id 확인 필요 (구 day0_chris_x1 start_cutscene)"),
    ("d1_tutorial_chris", 2,  "enter", "chris", "R", "", "", "", "", "구 slot right / enter_effect silhouette_reveal, sfx_mode default_only — 신 구조 미지원, 연출 참고용"),
    ("d1_tutorial_chris", 3,  "say", "chris", "default", "루나.", "Luna.", "", "", "구 x3"),
    ("d1_tutorial_chris", 4,  "say", "luna", "default", "네?", "Yes?", "", "", ""),
    ("d1_tutorial_chris", 5,  "say", "chris", "default", "방금 내가 무슨 말을 했는지 듣긴 한 거야?", "Did you hear a word of what I just said?", "", "", ""),
    ("d1_tutorial_chris", 6,  "say", "luna", "default", "무슨 말이요?", "What did you say?", "", "", ""),
    ("d1_tutorial_chris", 7,  "say", "chris", "fail", ".....", ".....", "", "", "expression 'fail' 확인 필요"),
    ("d1_tutorial_chris", 8,  "say", "chris", "default", "집중해. 이제 와서 관두지도 못한다고.", "Focus. It's too late to quit now.", "", "", ""),
    ("d1_tutorial_chris", 9,  "say", "luna", "default", "네. 알겠습니다.", "Yes. Understood.", "", "", ""),
    ("d1_tutorial_chris", 10, "say", "chris", "default", "그럼 방금 배웠던 내용을 다시 짚어보자.", "Then let's go over what you just learned.", "", "", ""),
    ("d1_tutorial_chris", 11, "say", "luna", "default", "알겠습니다.", "Understood.", "", "", ""),
    ("d1_tutorial_chris", 12, "say", "chris", "default", "<order>드라이 마티니</order> 하나만 만들 수 있게 되면 더는 확인하지 않을 거야.\n금방 하는 거니까 지루해도 참아.", "Once you can make a single <order>Dry Martini</order>, I'll stop checking on you.\nIt won't take long, so bear with the boredom.", "", "", ""),
    ("d1_tutorial_chris", 13, "say", "luna", "default", "(건조한 마티니? 축축한 마티니는 무슨 맛일까.)", "(A dry martini? I wonder what a wet one tastes like.)", "", "", "구 type monologue"),
    ("d1_tutorial_chris", 14, "say", "chris", "fail", "또 딴생각하지.", "You're drifting off again.", "", "", ""),
    ("d1_tutorial_chris", 15, "say", "luna", "default", "아니요. 바로 시작하죠.", "No. Let's start right away.", "", "", ""),
    ("d1_tutorial_chris", 16, "say", "chris", "default", "좋아.", "Good.", "", "", ""),
    ("d1_tutorial_chris", 17, "say", "chris", "default", "먼저 손님의 주문을 받은 뒤 칵테일을 만드는 상황이 되면\n바 스테이션으로 화면이 전환될 거야.", "First — once you've taken a guest's order and it's time to mix,\nthe view will switch over to the bar station.", "", "", "UI 튜토리얼 구간 시작"),
    ("d1_tutorial_chris", 18, "say", "chris", "default", "그때 너의 시각 인터페이스에 칵테일을 만들 때 필요한 정보들이 출력될 거야.", "That's when your visual interface will display everything you need to build the cocktail.", "", "", ""),
    ("d1_tutorial_chris", 19, "say", "chris", "default", "먼저 좌측 상단에는 <name>손님의 주문</name>이 정리되어서 보일 텐데,\n혹시라도 손님의 주문을 잊었다면 여기서 확인하면 돼.", "At the top left you'll see the <name>guest's order</name>, laid out clean.\nIf you ever forget what they asked for, check it there.", "", "", ""),
    ("d1_tutorial_chris", 20, "say", "chris", "default", "좌측 주문 정보 아래에서 칵테일 레시피를 확인할 수 있어.", "Below the order info on the left, you can browse cocktail recipes.", "", "", ""),
    ("d1_tutorial_chris", 21, "say", "chris", "default", "보고 싶은 칵테일을 눌러보면 그 칵테일을 만드는 데\n필요한 <world>재료</world>, <world>제조 방법</world>, <world>설명</world> 등이 보일 거야.", "Tap the cocktail you want and you'll see its\n<world>ingredients</world>, <world>method</world>, <world>description</world> — everything it takes.", "", "", ""),
    ("d1_tutorial_chris", 22, "say", "chris", "default", "전에 이식한 <name>바텐더 가이드 칩</name>에 대부분의 칵테일 <name>레시피</name>가 들어 있어.\n하지만 지금은 레시피 정보가 조금밖에 안 보일 거야.", "The <name>bartender guide chip</name> we implanted holds most of the cocktail <name>recipes</name>.\nFor now, though, you'll only see a handful of them.", "", "", ""),
    ("d1_tutorial_chris", 23, "say", "luna", "default", "이유가 있습니까?", "Is there a reason?", "", "", ""),
    ("d1_tutorial_chris", 24, "say", "chris", "default", "“드라이 마티니 하나도 제대로 만들지 못한다면,\n다른 칵테일을 배울 필요도 없다.”이게 전에 있던 마스터가 남긴 방침이야.", "\"If you can't make a single Dry Martini properly,\nyou have no business learning any other cocktail.\" That was the old master's policy.", "", "", ""),
    ("d1_tutorial_chris", 25, "say", "luna", "default", "옳은 생각인 것 같습니다.", "That sounds like sound reasoning.", "", "", ""),
    ("d1_tutorial_chris", 26, "say", "chris", "default", "동감이다. 그래서 지금 네가 만들 수 있는 칵테일은 몇 개 안 돼.", "Agreed. Which is why you can only make a few cocktails right now.", "", "", ""),
    ("d1_tutorial_chris", 27, "say", "chris", "default", "계속 일하면서 <name>숙련도</name>가 쌓이면 만들 수 있는 칵테일이 늘어날 거야.", "Keep working, build up your <name>proficiency</name>, and the list will grow.", "", "", ""),
    ("d1_tutorial_chris", 28, "say", "luna", "default", "숙련도를 어떻게 확인하는 거죠?", "How do I check my proficiency?", "", "", ""),
    ("d1_tutorial_chris", 29, "say", "chris", "default", "네가 손님의 주문에 맞는 칵테일을 주거나, 제조 과정을 완벽하게 수행한다면\n바텐더 가이드 칩이 분석해서 숙련도를 기록할 거야.", "When you serve what the guest actually ordered, or nail the mixing process,\nthe guide chip analyzes it and logs your proficiency.", "", "", ""),
    ("d1_tutorial_chris", 30, "say", "chris", "default", "일정 수준에 도달하면 <name>새로운 레시피</name>도 열릴 테고.", "Reach a certain level, and <name>new recipes</name> will unlock too.", "", "", ""),
    ("d1_tutorial_chris", 31, "say", "luna", "default", "생각보다 유용한 칩이었네요.", "The chip is more useful than I expected.", "", "", ""),
    ("d1_tutorial_chris", 32, "say", "chris", "default", "그거 만들겠다고 전 마스터가 고생 좀 했지.", "The old master went through hell building that thing.", "", "", ""),
    ("d1_tutorial_chris", 33, "say", "chris", "default", "메뉴에서 레시피를 고르면 선반이 차례로 나온다.\n잔, 도구, 가니시, 재료 순서야. 필요한 걸 골라 담으면 돼.", "Pick a recipe from the menu and the shelves come one by one —\nglass, tools, garnish, then ingredients. Take what you need.", "", "", ""),
    ("d1_tutorial_chris", 34, "say", "chris", "default", "잘못 담았으면 다시 눌러서 빼면 되고, 화살표로 앞 선반에\n돌아갈 수도 있어. 다 담았으면 '제조 시작'이다.", "Tap again to put something back, or use the arrows to revisit\na shelf. When you have everything, hit 'Start'.", "", "", ""),
    ("d1_tutorial_chris", 35, "say", "luna", "default", "제조 과정은 <world>쉐이킹</world>, <world>스터</world>, <world>빌드</world>, 이렇게 세 가지로 분류되는 것이 맞나요?", "The methods fall into three categories — <world>shaking</world>, <world>stirring</world>, and <world>building</world>. Is that correct?", "", "", ""),
    ("d1_tutorial_chris", 36, "say", "chris", "default", "기억은 하는군. 각 방법이 뭐가 다른지에 대한 설명도 필요하나?", "So you do remember. Need me to explain how they differ?", "", "", ""),
    ("d1_tutorial_chris", 37, "say", "luna", "default", "원활한 업무를 위해 필요할 것 같습니다.", "It would help me operate smoothly.", "", "", ""),
    ("d1_tutorial_chris", 38, "say", "chris", "default", "좋아. 먼저 <world>쉐이킹</world>은 보스턴 쉐이커에 재료를 담은 뒤\n위아래로 강하게 흔들면서 섞는 방법이다.", "Fine. <world>Shaking</world> first: load the ingredients into a Boston shaker\nand mix them hard, shaking up and down.", "", "", ""),
    ("d1_tutorial_chris", 39, "say", "chris", "default", "잘 안 섞이는 재료들이 들어갈 때 주로 사용하지.", "You mostly use it for ingredients that don't blend easily.", "", "", ""),
    ("d1_tutorial_chris", 40, "say", "chris", "default", "<world>스터</world>는 믹싱 글라스에 재료를 넣고 바 스푼으로 천천히 저어 만드는 방법이다.\n재료를 강하게 섞을 필요가 없거나, 향과 맛을 섬세하게 살릴 때 자주 사용해.", "<world>Stirring</world> means adding the ingredients to a mixing glass and slowly stirring with a bar spoon.\nUse it when the mix doesn't need force, or when the aroma and flavor should stay delicate.", "", "", ""),
    ("d1_tutorial_chris", 41, "say", "chris", "default", "<world>빌드</world>는 완성 잔에 재료를 직접 넣어서 만드는 방식이다.\n자연스럽게 섞이는 재료나 탄산이 들어가는 칵테일에 주로 사용하지.", "<world>Building</world> means pouring the ingredients straight into the serving glass.\nIt's for things that blend on their own, or anything with carbonation.", "", "", ""),
    ("d1_tutorial_chris", 42, "say", "chris", "default", "여기까지 이해했나.", "Following so far?", "", "", ""),
    ("d1_tutorial_chris", 43, "say", "luna", "default", "평범한 사람이라면 전부 기억하기 힘들 것 같습니다.", "An ordinary person would struggle to remember all of this.", "", "", ""),
    ("d1_tutorial_chris", 44, "say", "chris", "default", "그래. 그래도 넌 <world>평범한 사람</world>이 아니잖아.", "Right. But then, you're no <world>ordinary person</world>.", "", "", ""),
    ("d1_tutorial_chris", 45, "say", "luna", "default", "저는 평범하다고 생각합니다.", "I consider myself ordinary.", "", "", ""),
    ("d1_tutorial_chris", 46, "say", "chris", "default", "...그렇게 생각하면 할 말은 없지.\n지금 몰라도 나중에 또 알려 줄 테니 괜찮을 거다.", "...If that's how you see it, I've got nothing to add.\nDon't worry — if it doesn't stick now, I'll walk you through it again later.", "", "", ""),
    ("d1_tutorial_chris", 47, "say", "chris", "default", "제조를 시작하면 담아둔 것들이 올바른 순서로 진행된다.\n술은 <name>목표선</name>에 맞춰 멈추고, 저을 땐 스푼으로 원을 그리면 돼.", "Once you start, everything you stocked plays out in proper order.\nStop the pour at the <name>target line</name>; stir by drawing circles with the spoon.", "", "", ""),
    ("d1_tutorial_chris", 48, "say", "chris", "default", "레시피의 <name>정량</name>에 가까울수록 <world>완성도</world>가 올라간다.\n헷갈리면 레시피 노트를 다시 봐도 좋아.", "The closer you are to the recipe's <name>exact measures</name>, the higher the <world>quality</world>.\nCheck the recipe note anytime you're unsure.", "", "", ""),
    ("d1_tutorial_chris", 49, "say", "chris", "default", "그리고 마무리로 손님한테 제공하면 끝이야.", "Then serve it to the guest, and you're done.", "", "", ""),
    ("d1_tutorial_chris", 50, "say", "luna", "default", "이해했습니다.", "Understood.", "", "", ""),
    ("d1_tutorial_chris", 51, "say", "chris", "default", "좋아. 그럼 <order>드라이 마티니</order> 한 잔 만들어 봐.", "Good. Now — make me a <order>Dry Martini</order>.", "", "", ""),
    ("d1_tutorial_chris", 52, "say", "luna", "default", "주문받았습니다.", "Order received.", "", "", ""),
    ("d1_tutorial_chris", 53, "say", "luna", "default", "(<order>드라이 마티니</order> 한 잔… 흔들지 말고, <order>저어서</order>.)", "(One <order>Dry Martini</order>... don't shake it — <order>stir</order>.)", "", "", "구 type monologue — 다음이 order(비 say) 스텝이라 루나 규칙 통과"),
    # --- 제조 (구 day0_chris_x54 start_craft → day0_chris_order1) ---
    ("d1_tutorial_chris", 54, "order", "chris", "exact:dry_martini", "드라이 마티니 한 잔. 흔들지 말고 저어서.", "One Dry Martini. Stirred, not shaken.", "", "", "주문대사는 day0_crafts.json order 필드 원문"),
    ("d1_tutorial_chris", 55, "craft", "", "tutorial:dry_martini", "", "", "", "", "구 craft_event day0_chris_order1 / finish 컷씬 day1_finish_default 미이식(CONFLICTS 참조)"),
    ("d1_tutorial_chris", 56, "serve", "chris", "", "", "", "", "", ""),
    # --- 판정 분기: perfect (구 d0c_react_perfect_001~004) ---
    ("d1_tutorial_chris", 57, "say", "luna", "default", "어떤가요?", "How is it?", "grade >= perfect", "", "판정 상 (perfect)"),
    ("d1_tutorial_chris", 58, "say", "chris", "success", "…생각보다 재능이 있군.", "...More talent than I expected.", "grade >= perfect", "affinity.chris += 5", "구 reactions.perfect affinity 5 / skill 3은 미이식"),
    ("d1_tutorial_chris", 59, "say", "luna", "default", "이제 반복 학습에서 벗어날 수 있나요?", "Does this mean I'm free from the repetition drills?", "grade >= perfect", "", ""),
    ("d1_tutorial_chris", 60, "say", "chris", "default", "그래. 기본적인 제조 수업은 끝이야.", "Yes. The basic mixing lessons are over.", "grade >= perfect", "", ""),
    # --- 판정 분기: good (구 d0c_react_good_001~007) ---
    ("d1_tutorial_chris", 61, "say", "luna", "default", "어떤가요?", "How is it?", "grade >= good && grade < perfect", "", "판정 중 (good)"),
    ("d1_tutorial_chris", 62, "say", "chris", "default", ".....", ".....", "grade >= good && grade < perfect", "", ""),
    ("d1_tutorial_chris", 63, "say", "luna", "default", "맛이 이상합니까?", "Does it taste wrong?", "grade >= good && grade < perfect", "", ""),
    ("d1_tutorial_chris", 64, "say", "chris", "default", "괜찮군.", "Not bad.", "grade >= good && grade < perfect", "affinity.chris += 1", "구 reactions.good affinity 1 / skill 2는 미이식"),
    ("d1_tutorial_chris", 65, "say", "chris", "default", "이 정도면 기본적인 제조법은 익힌 것 같아.", "At this level, I'd say you've got the basics down.", "grade >= good && grade < perfect", "", ""),
    ("d1_tutorial_chris", 66, "say", "luna", "default", "다행이네요.", "That's a relief.", "grade >= good && grade < perfect", "", ""),
    ("d1_tutorial_chris", 67, "say", "chris", "default", "아직 개선할 부분은 있지만, 나머지는 일하면서 익히면 되겠어.", "There's still room to improve, but the rest you can pick up on the job.", "grade >= good && grade < perfect", "", ""),
    ("d1_tutorial_chris", 68, "say", "luna", "default", "확인했습니다.", "Acknowledged.", "grade >= good && grade < perfect", "", ""),
    # --- 판정 분기: normal = 다른 칵테일 제출 (구 d0c_react_normal_001~006 → start_craft 재진입 루프를 재도전 1회로 평탄화) ---
    ("d1_tutorial_chris", 69, "say", "chris", "fail", "이건 내가 말한 칵테일이 아닌데.", "This isn't the cocktail I asked for.", "grade < good", "", "구 평가 규칙상 grade<good = 다른 칵테일 제출"),
    ("d1_tutorial_chris", 70, "say", "luna", "default", "다른 칵테일의 레시피를 확인한 것 같네요.", "It seems I checked the wrong recipe.", "grade < good", "", ""),
    ("d1_tutorial_chris", 71, "say", "chris", "default", "이런 식이면 곤란한데, 루나.\n제대로 만들어.", "This won't do, Luna.\nMake it properly.", "grade < good", "", ""),
    ("d1_tutorial_chris", 72, "say", "luna", "default", "네, 알겠습니다.", "Yes, understood.", "grade < good", "", ""),
    ("d1_tutorial_chris", 73, "say", "luna", "default", "(<order>드라이 마티니</order> 한 잔이야… 제대로 확인해 보자.)", "(One <order>Dry Martini</order>... let's check it properly this time.)", "grade < good", "", "구 type monologue — 다음이 order 스텝이라 루나 규칙 통과"),
    ("d1_tutorial_chris", 74, "order", "chris", "exact:dry_martini", "드라이 마티니 한 잔. 흔들지 말고 저어서.", "One Dry Martini. Stirred, not shaken.", "grade < good", "", "재도전 1회 — 원문은 무한 루프(CONFLICTS 참조)"),
    ("d1_tutorial_chris", 75, "craft", "", "order", "", "", "grade < good", "", ""),
    ("d1_tutorial_chris", 76, "serve", "chris", "", "", "", "grade < good", "", "재도전 후 판정 대사 없음 — 원문 루프 평탄화의 한계"),
    # ---------- d1_tutorial_wrap : 합류 지점 (구 d0c_end_001~x26) ----------
    ("d1_tutorial_wrap", 1,  "say", "chris", "default", "방금은 내가 원하는 칵테일을 정확히 주문했지만,\n손님에 따라서는 주문을 <world>애매하게</world> 하거나 <world>칵테일 선택</world>을 맡길 수도 있어.", "Just now I told you exactly what I wanted — but some guests\nwill order <world>vaguely</world>, or leave the <world>choice of cocktail</world> entirely to you.", "", "", "판정 분기 합류 지점"),
    ("d1_tutorial_wrap", 2,  "say", "luna", "default", "그러면 제 마음대로 만들어 주면 되는 건가요?", "Then I may make whatever I like?", "", "", ""),
    ("d1_tutorial_wrap", 3,  "say", "chris", "default", "그래도 되겠지. 하지만 아무 생각 없이 만들어서는 안 돼.", "You could. But never mix without thinking.", "", "", ""),
    ("d1_tutorial_wrap", 4,  "say", "luna", "default", "그러면 어떻게 해야 하죠?", "Then what should I do?", "", "", ""),
    ("d1_tutorial_wrap", 5,  "say", "chris", "default", "애매한 주문이라도 최대한 <world>의도</world>를 파악하려고 해 봐.\n눈앞에 있는 손님이 어떤 맛을 좋아할지도 생각해 보고.", "Even with a vague order, try to read the <world>intent</world> behind it.\nAnd think about what the guest in front of you might actually enjoy.", "", "", ""),
    ("d1_tutorial_wrap", 6,  "say", "luna", "default", "크리스도 알다시피 저는 타인의 취향을 짐작하는 일에는 익숙하지 않습니다.", "As you well know, Chris, guessing other people's tastes is not something I'm used to.", "", "", ""),
    ("d1_tutorial_wrap", 7,  "say", "chris", "default", "뭐든 해 보려는 마음가짐이 중요한 거지.", "What matters is the willingness to try.", "", "", ""),
    ("d1_tutorial_wrap", 8,  "say", "chris", "default", "헷갈리면 가이드 칩에 기록된 <name>칵테일 설명</name>을 읽어 봐.\n어떤 사람에게 어울리는지 판단하는 데 도움이 될 거야.", "If you get lost, read the <name>cocktail descriptions</name> on the guide chip.\nThey'll help you judge who a drink suits.", "", "", ""),
    ("d1_tutorial_wrap", 9,  "say", "chris", "default", "거기에 맛을 기준으로 <name>필터링</name>하는 기능도 있으니까\n그걸 활용해도 좋고.", "There's also a <name>filter</name> that sorts by flavor.\nFeel free to lean on that, too.", "", "", ""),
    ("d1_tutorial_wrap", 10, "say", "luna", "default", "노력해 보겠습니다.", "I will try.", "", "", ""),
    ("d1_tutorial_wrap", 11, "say", "chris", "default", "좋아. 처음에는 그렇게 시작하는 거지.", "Good. That's how everyone starts.", "", "", ""),
    ("d1_tutorial_wrap", 12, "say", "luna", "default", "아직 배워야 될 게 또 남았나요?", "Is there more I need to learn?", "", "", ""),
    ("d1_tutorial_wrap", 13, "say", "chris", "default", "음... 바텐더의 마음가짐이라든가,\n손님 대하는 방법 같은 것들도 알려 줘야 하지만…", "Hm... there's still the bartender's mindset,\nhow to handle guests, that sort of thing...", "", "", ""),
    ("d1_tutorial_wrap", 14, "say", "luna", "default", ".....", ".....", "", "", ""),
    ("d1_tutorial_wrap", 15, "say", "chris", "default", "…그래. 오늘은 이 정도면 충분하겠지.\n나머지는 일하면서 배우는 걸로.", "...Right. This is enough for today.\nYou'll learn the rest on the job.", "", "", ""),
    ("d1_tutorial_wrap", 16, "say", "chris", "default", "이제 가게에서는 크리스 말고 보스라고 불러.", "From now on, in the bar, it's not 'Chris' — call me 'Boss.'", "", "", ""),
    ("d1_tutorial_wrap", 17, "say", "luna", "default", "이유가 있습니까?", "Is there a reason?", "", "", ""),
    ("d1_tutorial_wrap", 18, "say", "chris", "default", "우리 가게 규칙이라고 생각하면 돼.\n나도 처음 왔을 때 그랬어.", "Think of it as a house rule.\nI did the same when I first came here.", "", "", ""),
    ("d1_tutorial_wrap", 19, "say", "luna", "default", "알겠습니다, 보스.", "Understood, Boss.", "", "", ""),
    ("d1_tutorial_wrap", 20, "say", "chris", "default", "오늘은 이걸로 끝이니까 먼저 집으로 가.", "That's it for today. Head home ahead of me.", "", "", ""),
    ("d1_tutorial_wrap", 21, "say", "luna", "default", "보스는 같이 안 가는 겁니까?", "You're not coming, Boss?", "", "", ""),
    ("d1_tutorial_wrap", 22, "say", "chris", "default", "그래. 원래 오늘은 쉬는 날이지만 거절할 수 없는 <world>손님</world>이 있어서 같이 못 가.", "No. Today was supposed to be my day off, but there's a <world>guest</world> I can't turn away.", "", "", "'거절할 수 없는 손님' — 후일 복선"),
    ("d1_tutorial_wrap", 23, "say", "chris", "default", "물론 앞으로도 교대 근무로 할 거라 출퇴근을 같이 하진 못할 거다.", "We'll be working in shifts from here on anyway, so don't expect us to commute together.", "", "", ""),
    ("d1_tutorial_wrap", 24, "say", "luna", "default", "알겠습니다.", "Understood.", "", "", ""),
    ("d1_tutorial_wrap", 25, "say", "chris", "default", "밖에서 처음 보는 사람이랑 말하거나 딴 길로 새지 말고 바로 집으로 가.", "Don't talk to strangers out there, and don't wander — go straight home.", "", "", ""),
    ("d1_tutorial_wrap", 26, "say", "luna", "default", "네, 보스.", "Yes, Boss.", "", "", ""),
]

# (choice_id, seq, text_ko, text_en, when, effects, goto, note)  — 8필드
CHOICES = [
    # day0.json에 choices 노드 없음 (모든 dialogues[].choices == null)
]
