# 구 day1.json → 새 day2 (바 2부) 변환
# 원본: Assets/StreamingAssets/day1.json (290노드, 단일 scene "day1_start") + day1_crafts.json
# 변환일: 2026-07-19

CONFLICTS = [
    "해금일 충돌 의심: day1_aili_order1의 정답 칵테일 cosmopolitan, day1_bubi_order1의 정답 칵테일 kahlua_milk — 신 해금표에서는 day5/6 해금. day2 등장과 충돌. 대체 칵테일 지정 또는 해금표 조정 필요.",
    "컷씬 id 확인 필요: day1_bubi_fetch (포트 부탁→부비 데려오기), day1_bubi_drink_reaction (부비 bad 반응). timeline 스텝으로 이식했으나 신 Cutscenes 표에 존재하는지 확인 필요. craft finish 컷씬 day1_finish_default는 크래프트 이벤트 설정 소관이라 스텝으로 미이식.",
    "판정 5단계 매핑: 구 판정 perfect/good/normal/miss/bad 5종 반응 대사를 when grade 비교로 게이트. grade 서열을 bad < miss < normal < good < perfect로 가정하고 'grade >= perfect', 'grade >= good && grade < perfect', 'grade >= normal && grade < good', 'grade >= miss && grade < normal', 'grade < miss'를 사용. 참고 DSL 예시에는 >= good / < good만 확인됨 — miss(주문과 다른 칵테일 서빙)가 신 엔진 grade 축에 존재하는지 확인 필요.",
    "비선형 점프 1 (재제조 루프): 포트 bad 반응 말미 d1p_react_bad_009가 start_craft(day1_port_order1)로 재진입하는 루프 — 신 선형 구조로 표현 불가. flag.d2_port_retry를 grade < miss일 때 세우고 order/craft/serve 1회 재시도로 대체. 재제조 후 판정 반응 대사는 재생되지 않음(합류 대사 d1p_after_001로 진행).",
    "비선형 점프 2 (condition_branch): d1end_001_x1이 type=condition_branch, next 없음 — 분기 기준 데이터가 노드에 없어 직전 set_flag(bubi_affinity_high) 기준 분기로 판단. d1end_bubi_*/d1end_normal_* 두 갈래를 when flag.bubi_affinity_high / !flag.bubi_affinity_high 게이트로 한 씬에 병합(공통 대사는 병합).",
    "비선형 점프 3 (부비 bad 갈래): d1b_react_bad_*는 부비 퇴장 후 d1b_after_nobubi_*로, good/perfect는 d1b_after_001로 합류 — 아일리 퇴장 대사가 양 갈래에서 동일 텍스트로 중복되어 있어 공통 스텝으로 병합하고, 퇴장 후 루나·부비 대화(d1b_after_001_x6~x9)만 flag.bubi_affinity_high로 게이트.",
    "알 수 없는 expression: 'event_surprise' (port, day1_start_x37) — 참고 표(default/joy/serious/anger/success/fail/drunk)에 없음. 원문 그대로 유지, Expressions 표 확인 필요.",
    "도달 불가 반응: 아일리 bad 반응(d1a_react_bad_001)은 구 evaluation rules상 생성 불가(오답은 전부 normal, bad_nm_fail도 normal) — grade < normal 게이트로 일단 유지.",
    "부비 order 대사: crafts json의 order 텍스트 '(고양이가 술을 마실 수 있었나?)'는 루나 독백 성격 — 규칙대로 order 스텝 화자(타겟)는 bubi로 두고 원문 유지. 어색하면 대사 교체 필요.",
    "루나 규칙 조정 없음/최소: craft 직전이 루나 독백이 되는 3곳(포트/아일리/부비 주문, 포트 재제조)은 order 스텝(손님 화자)을 craft 직전에 삽입하는 방식으로 해소 — 원문 대사 순서는 그대로 보존됨. 단 order 스텝 텍스트는 crafts json의 주문문이라 직전 say와 내용이 일부 중복.",
    "<name>...</name> 마크업 태그(진피즈 등 강조)는 text_ko/text_en에 원문 그대로 유지 — 신 엔진 태그 지원 확인 필요.",
    "per-grade 보상 수치(crafts json reactions의 affinity +5/+2/-2, tip_rate 0.1, pay_price 등)는 신 구조의 등급 반응 프리셋/정산 소관으로 판단해 effects로 미이식 — 프리셋 표와 대조 필요.",
    "enter 연출(silhouette_reveal, enter_duration, sfx_mode)은 스텝 note에만 기재 — 신 구조 이식 방법 확인 필요.",
    "구 flag id 'bubi_affinity_high' 그대로 사용 — 신 플래그 명명 규칙과 대조 필요.",
    "speaker 매핑 충돌 없음: 등장 화자 luna/chris/port/aili/bubi 전부 허용 목록 내. system 노드는 전부 트리거 전용(텍스트 없음)이라 sign 화자 미사용.",
    "구 단일 씬(day1_start)을 손님 등장~퇴장 단위 6씬으로 분할. 부비 good 루트에서는 부비가 day_end까지 퇴장하지 않음(원문 동일) — 파트 종료 시 스테이지 정리 정책 확인 필요.",
]

# SCENE_COLS = ["id","day","phase","seq","trigger","when","title"]
SCENES = [
    ("d2_open",        2, "bar", 1, "auto",   "", "개점 — 크리스와 교대 전 당부"),
    ("d2_port",        2, "bar", 2, "auto",   "", "포트 첫 방문 — 진피즈, 조니 이야기, 부비 배달"),
    ("d2_aili",        2, "bar", 3, "auto",   "", "아일리 등장 — 박스 위의 레이디"),
    ("d2_aili_lady_q", 2, "bar", 0, "manual", "", "분기 — 섹시한 레이디란 무엇인가"),
    ("d2_aili_craft",  2, "bar", 4, "auto",   "", "아일리 주문 — 그리고 부비의 한 잔"),
    ("d2_close",       2, "bar", 5, "auto",   "", "마감 — 크리스 교대"),
]

# STEP_COLS = ["scene_id","seq","type","actor","arg","text_ko","text_en","when","effects","note"]
STEPS = [
    # ---------- d2_open : 크리스 개점 당부 (x1~x26) ----------
    ("d2_open", 1,  "enter", "chris", "R", "", "", "", "", "원 x1. silhouette_reveal 0s"),
    ("d2_open", 2,  "say", "chris", "default", "좋아. 그럼 부탁한다.", "Alright. Then I'm counting on you.", "", "", ""),
    ("d2_open", 3,  "say", "luna", "default", "네, 크리스.", "Yes, Chris.", "", "", ""),
    ("d2_open", 4,  "say", "chris", "default", "보스.", "Boss.", "", "", ""),
    ("d2_open", 5,  "say", "luna", "default", "네, 보스.", "Yes, Boss.", "", "", ""),
    ("d2_open", 6,  "say", "chris", "default", "그래. 오늘이 첫날인데 너무 긴장하진 말고.\n물론 넌 안 할 것 같지만.", "Good. It's your first day, so don't be too nervous.\nNot that you seem capable of it.", "", "", ""),
    ("d2_open", 7,  "say", "luna", "default", "저도 긴장할 때가 있습니다.", "I do get nervous sometimes.", "", "", ""),
    ("d2_open", 8,  "say", "chris", "default", "..너가?", "..You?", "", "", ""),
    ("d2_open", 9,  "say", "luna", "default", "개와 흡사하게 생긴 사람을 보면 거부 반응을 일으킵니다.", "I experience a rejection response when I see people who closely resemble dogs.", "", "", ""),
    ("d2_open", 10, "say", "chris", "default", "…무슨 이유인지 물어보진 않겠다.", "...I'm not going to ask why.", "", "", ""),
    ("d2_open", 11, "say", "luna", "default", "네, 보스.", "Yes, Boss.", "", "", ""),
    ("d2_open", 12, "say", "chris", "default", "좋아. 그럼 자정 전까지만 부탁해.\n그 이후엔 나랑 교대할 거야.", "Alright. You've got the counter until midnight.\nAfter that, I'll take over.", "", "", ""),
    ("d2_open", 13, "say", "chris", "default", "그리고 오늘부터 매일 유지비를 계속 내야 하니까 알아둬.", "And heads up — starting today, you pay the daily upkeep.", "", "", "유지비 시스템 안내"),
    ("d2_open", 14, "say", "luna", "default", "그걸 제가 내는 건가요?", "I'm the one paying that?", "", "", ""),
    ("d2_open", 15, "say", "chris", "default", "그래. 언제까지 놀고먹을 수는 없어.\n사회로 나왔으면 자기 몫은 해야지.", "That's right. You can't freeload forever.\nYou're out in the world now — pull your own weight.", "", "", ""),
    ("d2_open", 16, "say", "luna", "default", "제가 생각하기엔 행복이란 건 \n일을 하지 않아도 되는 삶인 것 같습니다.", "In my analysis, happiness is\na life where one does not have to work.", "", "", ""),
    ("d2_open", 17, "say", "chris", "default", "너 오늘 첫 출근이야. 앓는 소리는 짬 차면 해.", "It's your first shift. Earn some seniority before you start whining.", "", "", ""),
    ("d2_open", 18, "say", "luna", "default", "노력해 보겠습니다.", "I will make an effort.", "", "", ""),
    ("d2_open", 19, "say", "chris", "default", "또 몰래 재료 먹으면 안 돼.", "And no sneaking bites of the ingredients again.", "", "", "올리브 복선"),
    ("d2_open", 20, "say", "luna", "default", "네. 알겠습니다.", "Yes. Understood.", "", "", ""),
    ("d2_open", 21, "say", "chris", "default", "그래, 간다.", "Right. I'm off.", "", "", ""),
    ("d2_open", 22, "exit", "chris", "", "", "", "", "", "원 x22. fade_out 0.5s"),
    ("d2_open", 23, "say", "luna", "default", "……", "......", "", "", ""),
    ("d2_open", 24, "say", "luna", "default", "이번엔 올리브를 한 번……", "This time, maybe an olive......", "", "", "몰래 재료 시식"),
    ("d2_open", 25, "say", "luna", "default", "……생각보다 기름지고 쓴맛이 느껴지네.", "......Oilier and more bitter than expected.", "", "", ""),
    ("d2_open", 26, "say", "luna", "default", "이게 라임이었나?", "Was this a lime?", "", "", ""),

    # ---------- d2_port : 포트 첫 방문 (x27~x52 + 반응 + d1p_after) ----------
    ("d2_port", 1,  "enter", "port", "R", "", "", "", "", "원 x27. silhouette_reveal 1.0s"),
    ("d2_port", 2,  "say", "port", "default", "뭐야. 진짜 여기서 일하고 있네.", "What the. You really do work here.", "", "", ""),
    ("d2_port", 3,  "say", "luna", "default", "아응넝하세요. 소응님.", "Wewcome in, shir. Guhd ebening.", "", "", "입에 올리브 문 발음"),
    ("d2_port", 4,  "say", "port", "default", "뭘 입에다 쳐 넣고 얘기하는 거야?", "What the hell are you talking with in your mouth?", "", "", ""),
    ("d2_port", 5,  "say", "luna", "default", "크흠. 아닙니다. 어서 오세요.", "Ahem. Nothing. Welcome in.", "", "", ""),
    ("d2_port", 6,  "say", "port", "default", "크리스가 와 보라고 한 이유가 있었구만?", "So Chris had a reason for telling me to drop by.", "", "", ""),
    ("d2_port", 7,  "say", "luna", "default", "손님으로 온 건가요?", "Are you here as a customer?", "", "", ""),
    ("d2_port", 8,  "say", "port", "default", "당연하지. 내가 그럼 여기 일하러 왔을까 봐?", "Obviously. What, you think I came here to work?", "", "", ""),
    ("d2_port", 9,  "say", "luna", "default", "확인했습니다. 혹시 옆에 있는 로봇은 무슨 로봇입니까?", "Confirmed. By the way, what is that robot next to you?", "", "", ""),
    ("d2_port", 10, "say", "port", "default", "뭐?", "What?", "", "", ""),
    ("d2_port", 11, "say", "port", "event_surprise", "ㅁ..뭐야! 니미랄!!!", "Wh..what the! Son of a—!!!", "", "", "expression 'event_surprise' — CONFLICTS 참조"),
    ("d2_port", 12, "say", "luna", "default", "키우는 게 아니였군요.", "So it is not a pet.", "", "", ""),
    ("d2_port", 13, "say", "port", "default", "흠.. 아까 폐기물 매립 구역에서 붙은 놈인가보군..", "Hm.. must've latched onto me back at the waste landfill zone..", "", "", ""),
    ("d2_port", 14, "say", "port", "default", "이 놈도 이따 가서 한번 손 봐야겠어.", "I'll have to take this one apart later too.", "", "", ""),
    ("d2_port", 15, "say", "luna", "default", "아재 주문을 부탁드립니다.", "Old-timer, your order, please.", "", "", ""),
    ("d2_port", 16, "say", "port", "default", "흠… 기다려 봐.", "Hmm... hold on.", "", "", ""),
    ("d2_port", 17, "say", "luna", "default", "아쉽지만 '기다려 봐'라는 술은 없습니다.", "Unfortunately, we do not carry a drink called 'Hold On.'", "", "", ""),
    ("d2_port", 18, "say", "port", "default", "야 이 또라이야 자꾸 그럴래?", "Hey, you lunatic, you gonna keep that up?", "", "", ""),
    ("d2_port", 19, "say", "port", "default", "크리스 이 자식은 대체 뭘 가르친 거야?", "What the hell did Chris even teach you?", "", "", ""),
    ("d2_port", 20, "say", "luna", "default", "보스가 나머지는 일하면서 배우라고 했습니다.", "Boss said I should learn the rest on the job.", "", "", ""),
    ("d2_port", 21, "say", "port", "default", "어쩐지 나보고 오늘 일찍 끝내고 오라더니…\n이 썩을 놈이 날 교육 자료로 써?", "No wonder he told me to close up early and come over...\nThat rotten bastard's using me as training material?", "", "", ""),
    ("d2_port", 22, "say", "luna", "default", "교육 자료로 쓰기엔 많이 노후된 걸로 보입니다.", "You appear too worn-out to serve as training material.", "", "", ""),
    ("d2_port", 23, "say", "port", "default", "……", "......", "", "", ""),
    ("d2_port", 24, "say", "port", "default", "……일단 <name>진피즈</name> 한 잔 줘. 정석대로.", "......Just get me a <name>Gin Fizz</name>. By the book.", "", "", ""),
    ("d2_port", 25, "say", "luna", "default", "네, 손님.", "Yes, sir.", "", "", ""),
    ("d2_port", 26, "say", "luna", "default", "(<name>진피즈</name> 한 잔. 정석대로.)", "(One <name>Gin Fizz</name>. By the book.)", "", "", "독백(monologue)"),
    ("d2_port", 27, "order", "port", "exact:gin_fizz", "진피즈, 정석대로.", "A Gin Fizz, by the book.", "", "", "day1_port_order1. craft 직전 손님 스텝(루나 규칙)"),
    ("d2_port", 28, "craft", "", "order", "", "", "", "", ""),
    ("d2_port", 29, "serve", "port", "", "", "", "", "", ""),
    # 판정 반응 — perfect (d1p_react_perfect_*)
    ("d2_port", 30, "say", "port", "default", "야!", "Hey!", "grade >= perfect", "", "판정 분기: perfect"),
    ("d2_port", 31, "say", "luna", "default", "왜요?", "Yes?", "grade >= perfect", "", ""),
    ("d2_port", 32, "say", "port", "default", "이거 왜 맛있어?", "Why does this taste good?", "grade >= perfect", "", ""),
    ("d2_port", 33, "say", "luna", "default", "혹시 주문이 맛없는 진피즈였습니까?", "Was your order for a bad Gin Fizz?", "grade >= perfect", "", ""),
    ("d2_port", 34, "say", "port", "joy", "아니. 그건 아니지만. 애송이가 만든 거라고 믿기지 않는군.", "No. It's not that. Just hard to believe a greenhorn made this.", "grade >= perfect", "", ""),
    ("d2_port", 35, "say", "luna", "default", "칭찬 감사합니다.\n나가실 때 추가 팁은 테이블 위에 올려두시면 됩니다.", "Thank you for the compliment.\nAdditional tips may be left on the table on your way out.", "grade >= perfect", "", ""),
    ("d2_port", 36, "say", "port", "serious", "…아직 손님 응대는 개판이지만.", "...Though your customer service is still a mess.", "grade >= perfect", "", ""),
    # 판정 반응 — good (d1p_react_good_*)
    ("d2_port", 37, "say", "port", "serious", "흠…", "Hmm...", "grade >= good && grade < perfect", "", "판정 분기: good"),
    ("d2_port", 38, "say", "luna", "default", "어떤가요?", "How is it?", "grade >= good && grade < perfect", "", ""),
    ("d2_port", 39, "say", "port", "joy", "생각보다 나쁘지않네.", "Not as bad as I expected.", "grade >= good && grade < perfect", "", ""),
    ("d2_port", 40, "say", "luna", "default", "칭찬입니까?", "Is that a compliment?", "grade >= good && grade < perfect", "", ""),
    ("d2_port", 41, "say", "port", "joy", "이제 막 시작한 애송이한테 이 정도면 칭찬이지.", "For a greenhorn who just started, that's a compliment, yeah.", "grade >= good && grade < perfect", "", ""),
    # 판정 반응 — normal (d1p_react_normal_*)
    ("d2_port", 42, "say", "port", "serious", "흐음.", "Hmmm.", "grade >= normal && grade < good", "", "판정 분기: normal"),
    ("d2_port", 43, "say", "luna", "default", "맛이 어떠십니까?", "How does it taste?", "grade >= normal && grade < good", "", ""),
    ("d2_port", 44, "say", "port", "serious", "진피즈긴 한데… 뭔가 어설퍼.", "It's a Gin Fizz, sure... but something's clumsy about it.", "grade >= normal && grade < good", "", ""),
    ("d2_port", 45, "say", "luna", "default", "제조 과정에서 완성도가 부족했던 것 같습니다.", "It appears the execution lacked polish.", "grade >= normal && grade < good", "", ""),
    ("d2_port", 46, "say", "port", "serious", "마시는 데 지장은 없어. 다음엔 좀 더 정성 들여.", "It's drinkable. Put more care into the next one.", "grade >= normal && grade < good", "", ""),
    # 판정 반응 — miss: 주문과 다른 칵테일 (d1p_react_miss_*)
    ("d2_port", 47, "say", "port", "default", "이야 대단한데?", "Wow, impressive.", "grade >= miss && grade < normal", "", "판정 분기: miss(오주문)"),
    ("d2_port", 48, "say", "luna", "default", "네?", "Pardon?", "grade >= miss && grade < normal", "", ""),
    ("d2_port", 49, "say", "port", "serious", "얼마나 자신있으면 시키지도 않은 술을 주는 거지?", "How confident do you have to be to serve a drink nobody ordered?", "grade >= miss && grade < normal", "", ""),
    ("d2_port", 50, "say", "luna", "default", "죄송합니다. 레시피를 다른 것으로 찾은 것 같습니다.", "My apologies. I appear to have pulled up the wrong recipe.", "grade >= miss && grade < normal", "", ""),
    ("d2_port", 51, "say", "port", "serious", "나 말고도 다른 손님한테 이러면 곤란할 텐데.", "You pull this on other customers, you're in trouble.", "grade >= miss && grade < normal", "", ""),
    ("d2_port", 52, "say", "luna", "default", "다시 만들어 드리겠습니다.", "I will make it again.", "grade >= miss && grade < normal", "", ""),
    ("d2_port", 53, "say", "port", "serious", "됐어. 그냥 마실 테니 다음부턴 실수하지 마.", "Forget it. I'll drink it — just don't slip up again.", "grade >= miss && grade < normal", "", ""),
    ("d2_port", 54, "say", "port", "serious", "하지만 내가 주문한 것도 아닌 걸 줬으니.\n돈은 못 내, 알았지?", "But since this isn't what I ordered,\nI'm not paying for it. Got it?", "grade >= miss && grade < normal", "", "구 데이터: pay_price=false"),
    ("d2_port", 55, "say", "luna", "default", "네, 알겠습니다.", "Yes, understood.", "grade >= miss && grade < normal", "", ""),
    # 판정 반응 — bad + 재제조 (d1p_react_bad_*)
    ("d2_port", 56, "say", "port", "default", "……", "......", "grade < miss", "", "판정 분기: bad"),
    ("d2_port", 57, "say", "luna", "default", "왜 아무 말도 없으십니까?", "Why are you not saying anything?", "grade < miss", "", ""),
    ("d2_port", 58, "say", "port", "anger", "이게 술이냐?", "You call this a drink?", "grade < miss", "", ""),
    ("d2_port", 59, "say", "luna", "default", "형식상으로는 그렇습니다.", "Technically, it qualifies as one.", "grade < miss", "", ""),
    ("d2_port", 60, "say", "port", "anger", "아니, 나는 내 미각을 마비시키는 무언가를 쓰레기라 부르기로 했어.", "No. I've decided to call anything that paralyzes my taste buds garbage.", "grade < miss", "", ""),
    ("d2_port", 61, "say", "luna", "default", "손님의 감각 기관에 손상을 줄 의도는 없었습니다.", "There was no intent to damage your sensory organs.", "grade < miss", "", ""),
    ("d2_port", 62, "say", "port", "anger", "사람한테 총을 쏴 놓고 고의가 아니라고 하는 등신 같은 갱놈들 같군.\n기회를 주지. 다시 만들어.", "You sound like those idiot gangers who shoot a man and claim it wasn't on purpose.\nI'll give you one more chance. Make it again.", "grade < miss", "", ""),
    ("d2_port", 63, "say", "luna", "default", "알겠습니다.", "Understood.", "grade < miss", "", ""),
    ("d2_port", 64, "say", "luna", "default", "(<name>진피즈</name> 한 잔. 레시피를 잘 확인하자.)", "(One <name>Gin Fizz</name>. Check the recipe carefully this time.)", "grade < miss", "", "독백. 원문은 여기서 start_craft 재진입(루프) — CONFLICTS 참조"),
    ("d2_port", 65, "effect", "", "", "", "", "grade < miss", "flag.d2_port_retry = true", "재제조 1회 게이트용 플래그"),
    ("d2_port", 66, "order", "port", "exact:gin_fizz", "진피즈, 정석대로.", "A Gin Fizz, by the book.", "flag.d2_port_retry", "", "재제조 — craft 직전 손님 스텝(루나 규칙)"),
    ("d2_port", 67, "craft", "", "order", "", "", "flag.d2_port_retry", "", ""),
    ("d2_port", 68, "serve", "port", "", "", "", "flag.d2_port_retry", "", "재제조 후 판정 반응 대사는 재생 안 됨"),
    # 합류 — 조니 이야기 (d1p_after_001~x34)
    ("d2_port", 69, "say", "port", "default", "네가 아무리 못 만들어도 크리스가 처음 만든 술보다는 훨씬 낫지.", "However badly you make it, it's still miles better than Chris's first drink.", "", "", "전 판정 합류 지점"),
    ("d2_port", 70, "say", "luna", "default", "보스가 만든 술은 맛이 없었습니까?", "Was the Boss's drink that bad?", "", "", ""),
    ("d2_port", 71, "say", "port", "serious", "마시면 인생을 다시 생각하게 되는 맛이었지.", "It was the kind of taste that makes you reconsider your whole life.", "", "", ""),
    ("d2_port", 72, "say", "luna", "default", "철학적인 맛이었나 보네요.", "A philosophical flavor, it seems.", "", "", ""),
    ("d2_port", 73, "say", "port", "serious", "아니. 대체 어쩌다 내가 휘발유 맛이 나는 술을 마시고 있는\n인생을 살게 되었는지 생각한 거야.", "No. I mean I sat there wondering how my life had come to the point\nwhere I was drinking something that tasted like gasoline.", "", "", ""),
    ("d2_port", 74, "say", "luna", "default", "지금은 어떤가요?", "And now?", "", "", ""),
    ("d2_port", 75, "say", "port", "serious", "처음보단 나아졌지만 여전히 쓰레기지.\n무슨 수로 지금까지 버틴 건지 참……", "Better than at first, but still garbage.\nHow this place survived is beyond me......", "", "", ""),
    ("d2_port", 76, "say", "luna", "default", "이전에 보스가 바를 닫으려고 생각한 적이 있다고 했습니다.", "The Boss once mentioned he'd thought about closing the bar.", "", "", ""),
    ("d2_port", 77, "say", "port", "anger", "뭐? 이 썩을 놈이 이 가게가 어떤 곳인 줄 알고 문을 닫아.", "What? That rotten punk — does he even know what this place is, talking about closing it?", "", "", ""),
    ("d2_port", 78, "say", "luna", "default", "보스가 운영하던 가게가 아니었습니까?", "Was it not the Boss's bar to begin with?", "", "", ""),
    ("d2_port", 79, "say", "port", "serious", "원래 이 바의 주인은 조니라는 친구였지.", "The original owner of this bar was a guy named Johnny.", "", "", "조니 떡밥"),
    ("d2_port", 80, "say", "port", "serious", "조니가 있었으면 언노운이 이렇게 되진 않았을 텐데.", "If Johnny were still around, Unknown wouldn't have ended up like this.", "", "", ""),
    ("d2_port", 81, "say", "luna", "default", "……", "......", "", "", ""),
    ("d2_port", 82, "say", "port", "default", "그래도 루나 널 보니 뭔가 달라질 수도 있을 것 같네.\n아직 애송이지만 말이야.", "Still, looking at you, Luna, maybe things could change around here.\nEven if you're still a greenhorn.", "", "", ""),
    ("d2_port", 83, "say", "port", "default", "계속 크리스가 운영했었으면 십중팔구 갱단 아지트가 되었겠지.", "If Chris had kept running it alone, odds are it'd be a gang hideout by now.", "", "", ""),
    ("d2_port", 84, "say", "luna", "default", "하지만 제가 배운 것들은 다 보스가 알려준 겁니다.", "But everything I know was taught to me by the Boss.", "", "", ""),
    ("d2_port", 85, "say", "port", "default", "무슨 이유인지 몰라도 그 자식은 조니한테 잘 배워 놓고\n술은 드럽게 못 만들어.", "For whatever reason, that punk learned everything from Johnny\nand still makes drinks like absolute filth.", "", "", ""),
    ("d2_port", 86, "say", "luna", "default", "일부러 못만드는 게 아닌가요?", "Could he be making them badly on purpose?", "", "", ""),
    ("d2_port", 87, "say", "port", "default", "그런 거라면 당장 저 문을 열고 면상에 한 방 꽂아주고 싶군.", "If that's the case, I'd like to walk through that door right now and plant one in his face.", "", "", ""),
    ("d2_port", 88, "say", "luna", "default", "흥미롭네요. 이런 건 처음 들었습니다.", "Interesting. I have never heard any of this.", "", "", ""),
    ("d2_port", 89, "say", "port", "default", "그래도 네 보스잖아. 너무 나쁘게 보지는 말라고.", "Still, he's your boss. Don't think too badly of him.", "", "", ""),
    ("d2_port", 90, "say", "luna", "default", "지금까지 보스를 욕한 건 포트 혼자였습니다.", "So far, the only one badmouthing the Boss has been you, Port.", "", "", ""),
    ("d2_port", 91, "say", "port", "serious", "…그래도 크리스가 술 만드는 것 이외에\n바텐더로서 뭘 해야 하는지는 잘 알고 있으니까 배워 둬.", "...Still, aside from the actual mixing,\nChris knows exactly what a bartender should be. Learn that from him.", "", "", ""),
    ("d2_port", 92, "say", "luna", "default", "네, 알겠습니다.", "Yes, understood.", "", "", ""),
    ("d2_port", 93, "say", "port", "default", "그래.", "Good.", "", "", ""),
    ("d2_port", 94, "say", "port", "default", "그나저나 내가 첫 손님인데 부탁 하나 해도 되지?", "By the way — I'm your first customer. Mind doing me a favor?", "", "", "부비 배달 부탁"),
    ("d2_port", 95, "say", "luna", "default", "여기는 유흥업소가 아닙니다.", "This is not that kind of establishment.", "", "", ""),
    ("d2_port", 96, "say", "port", "default", "뭔 헛소리야? 그딴 주문 말고 다른 거.", "What kind of nonsense is that? Not that kind of favor — something else.", "", "", ""),
    ("d2_port", 97, "say", "luna", "default", "말씀하세요.", "Go ahead.", "", "", ""),
    ("d2_port", 98, "say", "port", "default", "밖에 나가면 고양이 한 마리가 자고 있을 텐데.\n데리고 와줘.", "There should be a cat sleeping right outside.\nBring it in for me.", "", "", ""),
    ("d2_port", 99, "say", "luna", "default", "혹시 바텐더 업무에 야생동물 포획이 포함되는 겁니까?", "Does bartending duty include the capture of wild animals?", "", "", ""),
    ("d2_port", 100, "say", "port", "joy", "내가 부탁이라고 했잖아. 나도 어찌 보면 생명의 은인인데,\n이 정도는 해 줄 수 있지?", "I said it was a favor. I did save your life, in a manner of speaking —\nyou can do this much for me, right?", "", "", "구조 은인 떡밥"),
    ("d2_port", 101, "say", "luna", "default", "보수가 충분하다면 못 할 일은 아닙니다.", "Given sufficient compensation, it is not impossible.", "", "", ""),
    ("d2_port", 102, "say", "port", "serious", "…내가 아주 골치 아픈 놈을 고쳐놨군.\n알겠으니까 부탁하지.", "...I really fixed up one troublesome piece of work.\nFine, fine. Please.", "", "", ""),
    ("d2_port", 103, "say", "luna", "default", "네, 손님.", "Yes, sir.", "", "", ""),
    ("d2_port", 104, "timeline", "", "day1_bubi_fetch", "", "", "", "", "컷씬 id 확인 필요"),
    ("d2_port", 105, "enter", "bubi", "M", "", "", "", "", "원 d1p_after_001_x36. silhouette_reveal 1.0s. L→M 이동: 2부 카메라(최대 1280×720)에 양 끝 좌석이 함께 안 잡혀 L+R 동시 배치 금지"),
    ("d2_port", 106, "say", "bubi", "default", "먀옹.", "Meow.", "", "", ""),
    ("d2_port", 107, "say", "port", "joy", "좋아. 잘 데려왔구먼.", "Good. Nicely done.", "", "", ""),
    ("d2_port", 108, "say", "luna", "default", "데려오라고 한 이유가 뭐죠?", "Why did you want it brought in?", "", "", ""),
    ("d2_port", 109, "say", "port", "default", "이번에 새로 찾은 물건이 있어서 살펴봐야되는데.\n부비가 옆에서 계속 방해를 하거든.", "I picked up a new find I need to look over,\nbut Bubi keeps getting in the way.", "", "", ""),
    ("d2_port", 110, "say", "luna", "default", "이 고양이의 이름이 부비인가요?", "Is this cat's name Bubi?", "", "", ""),
    ("d2_port", 111, "say", "port", "joy", "맞아. 그럼 먼저 일어난다.\n잘 부탁할게.", "That's right. Well, I'm off.\nTake good care of her.", "", "", ""),
    ("d2_port", 112, "say", "luna", "default", "네? 어디 가세요?", "Pardon? Where are you going?", "", "", ""),
    ("d2_port", 113, "say", "port", "joy", "크크. 오랜만에 제대로 된 작업을 할 수 있겠구먼.", "Heh heh. Finally, some proper work after all this time.", "", "", ""),
    ("d2_port", 114, "exit", "port", "", "", "", "", "", "원 d1p_after_001_x45. fade_out 0.5s"),
    ("d2_port", 115, "say", "luna", "default", "……", "......", "", "", ""),
    ("d2_port", 116, "say", "bubi", "default", "먀옹.", "Meow.", "", "", ""),
    ("d2_port", 117, "say", "luna", "default", "…이런 건 생각 못했는데.", "...I did not anticipate this.", "", "", ""),
    ("d2_port", 118, "say", "bubi", "default", "먀옹.", "Meow.", "", "", ""),
    ("d2_port", 119, "say", "luna", "default", "혹시 올리브를 좋아하시나요?", "Do you happen to like olives?", "", "", ""),
    ("d2_port", 120, "say", "bubi", "default", "먀옹.", "Meow.", "", "", ""),

    # ---------- d2_aili : 아일리 등장 (d1p_after_001_x52~x81) ----------
    ("d2_aili", 1,  "enter", "aili", "R", "", "", "", "", "원 d1p_after_001_x52. silhouette_reveal 1.0s"),
    ("d2_aili", 2,  "say", "aili", "default", "손님 받아라!!!", "Customer coming through!!!", "", "", ""),
    ("d2_aili", 3,  "say", "luna", "default", "어서 오세요, 손님.", "Welcome in, ma'am.", "", "", ""),
    ("d2_aili", 4,  "say", "aili", "default", "오랜만이야, 이쁜이. 진짜 여기서 일하고 있었구나.", "Long time no see, cutie. So you really are working here.", "", "", ""),
    ("d2_aili", 5,  "say", "luna", "default", "네? 누가 말해주던가요?", "Pardon? Who told you?", "", "", ""),
    ("d2_aili", 6,  "say", "aili", "default", "방금 여기서 도망간 영감이 말해줬지.\n나한테 여기로 꺼지라는 말과 함께.", "The old man who just fled this place told me.\nRight along with 'get lost and head to the bar.'", "", "", ""),
    ("d2_aili", 7,  "say", "luna", "default", "이해했습니다. 두 분 다 위에 있는 수리점에서\n같이 일하고 있었죠?", "Understood. You both work together\nat the repair shop upstairs, correct?", "", "", ""),
    ("d2_aili", 8,  "say", "aili", "default", "맞아. 서로 하는 일은 좀 다르지만 말이야.", "Right. Though what we each do is a little different.", "", "", ""),
    ("d2_aili", 9,  "say", "luna", "default", "혹시 그분은 길고양이 유기가 취미인가요?", "Is abandoning stray cats a hobby of his?", "", "", ""),
    ("d2_aili", 10, "say", "aili", "default", "큭큭. 그 영감 취미가 제정신은 아니긴 해.\n근데 쟨 할배가 전부터 키우던 고양이야.", "Heh heh. The old man's hobbies aren't exactly sane, true.\nBut that one's a cat he's kept for ages.", "", "", ""),
    ("d2_aili", 11, "say", "luna", "default", "무슨 이유로 저한테 맡긴 걸까요?", "Why would he leave her with me?", "", "", ""),
    ("d2_aili", 12, "say", "aili", "default", "몰라. 오늘 혼자서 만들고 싶은 게 있다고 그러던데.", "No idea. He said there was something he wanted to build alone today.", "", "", ""),
    ("d2_aili", 13, "say", "aili", "default", "나도 쫓겨났다니까?\n빌어먹을 영감탱이.", "He kicked me out too, you know?\nDamn old geezer.", "", "", ""),
    ("d2_aili", 14, "say", "luna", "default", "흠. 곤란하네요. 아직 동물을 다루는 방법은 배우지 못했습니다.", "Hm. This is problematic. I have not yet learned how to handle animals.", "", "", ""),
    ("d2_aili", 15, "say", "aili", "default", "걱정 마. 부비가 평범한 고양이는 아니거든.", "Don't worry. Bubi's no ordinary cat.", "", "", ""),
    ("d2_aili", 16, "say", "luna", "default", "이름이 부비인가요?", "Her name is Bubi?", "", "", ""),
    ("d2_aili", 17, "say", "aili", "default", "맞아. 나름 이 동네에서 악명을 떨치는 고양이니까 \n놀러 오면 잘 대접해주라고.", "Yep. She's got quite the reputation around this neighborhood,\nso treat her well when she visits.", "", "", ""),
    ("d2_aili", 18, "say", "bubi", "default", "먀옹.", "Meow.", "", "", ""),
    ("d2_aili", 19, "say", "luna", "default", "네. 향후 바텐더 업무 내용에 참고하겠습니다.", "Noted. I will factor it into future bartending duties.", "", "", ""),
    ("d2_aili", 20, "say", "luna", "default", "그리고 혹시 왜 의자에 앉지 않는 건지 알려주실 수 있나요?", "Also, may I ask why you will not sit on a chair?", "", "", ""),
    ("d2_aili", 21, "say", "aili", "default", "난 날 내려다 보는 사람이 있으면 \n면상에 총알을 박아주고 싶은 병이있어.", "I've got this condition — when someone looks down on me,\nI want to put a bullet in their face.", "", "", ""),
    ("d2_aili", 22, "say", "luna", "default", "그런 병은 처음 들어 봤습니다.", "I have never heard of such a condition.", "", "", ""),
    ("d2_aili", 23, "say", "aili", "default", "음음. 그럴 수 있어. 이건 희귀한 병이기 때문이지.", "Mm-hm. Understandable. It's a very rare condition.", "", "", ""),
    ("d2_aili", 24, "say", "aili", "fail", "아무튼 내가 의자에 앉으면 다른 사람들이 건방지게 날 깔본단 말이야.", "Anyway, when I sit on a chair, people get cocky and look down on me.", "", "", ""),
    ("d2_aili", 25, "say", "luna", "default", "그래서 그 박스를 밟고 서 계신 겁니까?", "Is that why you are standing on that box?", "", "", ""),
    ("d2_aili", 26, "say", "aili", "fail", "맞아 이 박스 덕분에 건방진 크리스가 아직 총에 맞지 않는거야.\n어떻게 보면 이 박스가 사람 하나 살려준 셈이지.", "Exactly. Thanks to this box, that cocky Chris hasn't been shot yet.\nIn a way, this box has saved a man's life.", "", "", ""),
    ("d2_aili", 27, "say", "luna", "default", "아하… 이해했습니다.", "Ah... understood.", "", "", ""),
    ("d2_aili", 28, "say", "aili", "default", "좋아. 그럼 슬슬 이쁜이가 만들어 주는 술 한 번 먹어 볼까?", "Alright. Time to try a drink made by my cutie, shall we?", "", "", ""),
    ("d2_aili", 29, "say", "luna", "default", "주문은 어떤 걸로 하시겠습니까?", "What would you like to order?", "", "", ""),
    ("d2_aili", 30, "say", "aili", "default", "음…\n나 같은 섹시한 레이디한테 어울리는 술로 부탁해.", "Hmm...\nMake me something that suits a sexy lady like myself.", "", "", "선택지 직전 손님 대사(루나 규칙 충족)"),
    ("d2_aili", 31, "choice", "", "ch_d2_aili_lady", "", "", "", "", "A: 딴 길(질문) → manual 씬 / B: 그대로 진행 → 다음 auto 씬 합류"),

    # ---------- d2_aili_lady_q : 분기 — 섹시한 레이디 질문 (d1a_q_001~x10, manual) ----------
    ("d2_aili_lady_q", 1,  "say", "luna", "default", "섹시한 레이디는 어떤 의미죠?", "What does 'sexy lady' mean, exactly?", "", "", ""),
    ("d2_aili_lady_q", 2,  "say", "aili", "default", "남녀 불문하고 내 매력에 빠져 돈이나 임플란트까지 뜯어다 바치는\n매력을 가진 레이디라는 거지.", "It means a lady so charming that men and women alike fall for her\nand hand over their money — even their implants.", "", "", ""),
    ("d2_aili_lady_q", 3,  "say", "luna", "default", "그런 적이 있나요?", "Has that ever actually happened?", "", "", ""),
    ("d2_aili_lady_q", 4,  "say", "aili", "default", "옛날에 KCPD 새끼들이 내 업장에 들이닥쳐서\n영업정지 때리기 전까진 자주 있었지.", "Happened all the time, back before those KCPD bastards\nstormed my establishment and shut it down.", "", "", "KCPD 세계관 떡밥"),
    ("d2_aili_lady_q", 5,  "say", "aili", "default", "그 이후로 KCPD랑 나한테 돈 빌려준 놈들이 아주 그냥\n발정 난 개새끼마냥 날 찾으려고 염병을 하더라고.", "Ever since, the KCPD and everyone I owe money to have been\nscrambling to find me like dogs in heat.", "", "", ""),
    ("d2_aili_lady_q", 6,  "say", "aili", "default", "별것도 아닌 일로 왜 그렇게 피곤하게 하는지.\n정말 할 짓 없는 자식들이라니까?", "All that fuss over nothing.\nSeriously, don't they have anything better to do?", "", "", ""),
    ("d2_aili_lady_q", 7,  "say", "luna", "default", "그렇다면 섹시한 레이디란 건 많은 이들한테 쫓겨서 피곤한 사람이란 거네요.", "So a 'sexy lady' is someone exhausted from being chased by many people.", "", "", ""),
    ("d2_aili_lady_q", 8,  "say", "aili", "default", "정확해. 내가 보기엔 루나 너도 재능이 충분히 있어 보여.\n어때? 나한테 배워볼 생각은?", "Exactly. And you know, Luna, I'd say you've got real talent.\nHow about it? Want to learn from me?", "", "", ""),
    ("d2_aili_lady_q", 9,  "say", "luna", "default", "거절합니다. 아직 일 시작한 지 하루밖에 되지 않았습니다.", "I decline. I have only been on this job for one day.", "", "", ""),
    ("d2_aili_lady_q", 10, "say", "aili", "default", "쯧. 재미없게 하긴.온다고 하면 크리스가 \n나한테 잔소리할 걸 생각하니 귀찮긴 하겠다.", "Tch. No fun at all. Then again, if you said yes,\nChris would nag me to death — what a hassle that'd be.", "", "", ""),
    ("d2_aili_lady_q", 11, "say", "aili", "default", "뭐, 어쨌든 빨리 술 한 잔 만들어줘 봐.", "Well, whatever. Hurry up and make me that drink.", "", "", "종료 후 다음 auto 씬(d2_aili_craft)으로 자연 합류"),

    # ---------- d2_aili_craft : 아일리 제조 + 부비의 한 잔 (d1a_craft_001~, d1a_after, d1b_*) ----------
    ("d2_aili_craft", 1,  "say", "luna", "default", "네, 주문 받았습니다.", "Yes, order received.", "", "", "합류 지점(원 d1a_craft_001)"),
    ("d2_aili_craft", 2,  "say", "luna", "default", "(자칭 <name>섹시한 레이디</name>에게 술 한 잔……)", "(One drink for the self-proclaimed <name>sexy lady</name>......)", "", "", "독백"),
    ("d2_aili_craft", 3,  "order", "aili", "exact:cosmopolitan", "섹시한 레이디한테 어울리는 술 한 잔..", "A drink fit for a sexy lady..", "", "", "day1_aili_order1. cosmopolitan은 신 해금표 day5 — CONFLICTS 참조"),
    ("d2_aili_craft", 4,  "craft", "", "order", "", "", "", "", ""),
    ("d2_aili_craft", 5,  "serve", "aili", "", "", "", "", "", ""),
    # 아일리 반응 — perfect (d1a_react_perfect_*)
    ("d2_aili_craft", 6,  "say", "aili", "success", "……뭐지?", "......What is this?", "grade >= perfect", "", "판정 분기: perfect"),
    ("d2_aili_craft", 7,  "say", "luna", "default", "왜 그러시죠?", "Is something wrong?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 8,  "say", "aili", "success", "존나 맛있어.\n왜 맛있지?", "It's damn delicious.\nWhy is it delicious?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 9,  "say", "luna", "default", "포트도 그렇고, 왜 다들 맛없는 술을 기대하고 오는 겁니까?", "Port was the same — why does everyone come in expecting a bad drink?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 10, "say", "aili", "default", "너 크리스가 만든 술 마셔 봤어?\n이거랑 비교하는 게 실례일 정도라니까.", "Have you ever tried a drink Chris made?\nComparing it to this would be an insult.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 11, "say", "luna", "default", "보스가 만든 술이 그렇게 맛없었습니까?", "Was the Boss's drink truly that bad?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 12, "say", "aili", "default", "손님으로 왔을 때 크리스가 처음 술을 만들어줬는데.\n한 모금 마시고 바로 크리스한테 잔을 던졌지.", "First time I came as a customer, Chris made me a drink.\nOne sip, and I threw the glass right at him.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 13, "say", "aili", "default", "음침하고 냄새나는 남자가 밸런타인데이랍시고 나한테 선물로 주려고\n한 달 동안 정성 들여 만든 초콜릿 맛이었어.", "It tasted like chocolate some creepy, smelly guy spent a whole month\nlovingly making as a Valentine's gift for me.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 14, "say", "luna", "default", "…무슨 맛이죠?", "...What flavor is that?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 15, "say", "aili", "default", "정성 들인 쓰레기. 형용할 수 없는 최악의 맛이지.", "Devoted garbage. The indescribable worst.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 16, "say", "luna", "default", "그건 그 사람의 노력을 무시하는 거 아닌가요?", "Is that not dismissive of that person's effort?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 17, "say", "aili", "default", "맞는 말이지만 넌 누군가가 정성을 들였다는 사실 하나만으로\n독약을 먹을 수 있을 것 같아?", "Fair point — but could you drink poison\njust because someone made it with love?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 18, "say", "luna", "default", "…..", ".....", "grade >= perfect", "", ""),
    ("d2_aili_craft", 19, "say", "aili", "default", "아무튼 크리스의 술을 마셨을 때는 그랬어.", "Anyway, that's what drinking Chris's stuff was like.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 20, "say", "luna", "default", "…그런 이야기는 듣지 못했습니다.", "...I was never told any of this.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 21, "say", "aili", "default", "크리스에 비하면 네가 만든 건 예술이지.\n처음 봤을 때 어느 정도 예상하긴 했지만, 기대 이상이네. 이쁜이.\n앞으로 자주 와야겠는걸?", "Compared to Chris, yours is a work of art.\nI had a feeling when I first saw you, but this exceeds expectations, cutie.\nI'll have to come by often, won't I?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 22, "say", "luna", "default", "감사합니다.", "Thank you.", "grade >= perfect", "", ""),
    # 아일리 반응 — good (d1a_react_good_*)
    ("d2_aili_craft", 23, "say", "aili", "success", "오. 괜찮은데?", "Oh. Not bad at all.", "grade >= good && grade < perfect", "", "판정 분기: good"),
    ("d2_aili_craft", 24, "say", "luna", "default", "주문 의도에 부합했습니까?", "Did it meet the intent of your order?", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 25, "say", "aili", "success", "완전 내 취향까지는 아닌데.\n그래도 초보자가 즉석에서 만든 것치곤 꽤 좋아.", "Not exactly my taste,\nbut for a beginner improvising on the spot, it's pretty good.", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 26, "say", "luna", "default", "그렇다면 실패는 아닌 것으로 판단하겠습니다.", "Then I will classify it as not a failure.", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 27, "say", "aili", "success", "응. 실패는 아니야.\n크리스 첫 술보단 이미 수십 배 낫다.", "Right. Not a failure.\nAlready dozens of times better than Chris's first drink.", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 28, "say", "luna", "default", "보스의 술은 평가 기준으로 자주 사용되는군요.", "The Boss's drink seems to be a frequently used benchmark.", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 29, "say", "aili", "default", "안 좋은 쪽으로는 전설이지.", "It's legendary — in the worst way.", "grade >= good && grade < perfect", "", ""),
    # 아일리 반응 — normal (d1a_react_normal_*; 구 규칙상 오답 칵테일 포함)
    ("d2_aili_craft", 30, "say", "aili", "default", "음……", "Hmm......", "grade >= normal && grade < good", "", "판정 분기: normal(오답 포함)"),
    ("d2_aili_craft", 31, "say", "luna", "default", "맛이 없습니까?", "Does it not taste good?", "grade >= normal && grade < good", "", ""),
    ("d2_aili_craft", 32, "say", "aili", "fail", "맛이 없다기보단.\n나한테 어울리는 술은 아닌 것 같네.", "It's not that it tastes bad.\nIt's just not the drink for me.", "grade >= normal && grade < good", "", ""),
    ("d2_aili_craft", 33, "say", "luna", "default", "섹시한 레이디라는 기준이 아직 모호합니다.", "The 'sexy lady' criterion remains ambiguous.", "grade >= normal && grade < good", "", ""),
    ("d2_aili_craft", 34, "say", "aili", "fail", "그걸 너무 진지하게 분석하지 마.\n그냥 느낌으로 가는 거야, 느낌.", "Don't analyze it so seriously.\nYou go by feel. Feel.", "grade >= normal && grade < good", "", ""),
    ("d2_aili_craft", 35, "say", "luna", "default", "느낌이란 건 추상적이라 좀 어렵습니다.", "Feel is abstract, and therefore difficult.", "grade >= normal && grade < good", "", ""),
    ("d2_aili_craft", 36, "say", "aili", "default", "인생은 원래 추상적이야. 그래서 재밌는 거지.", "Life is abstract by nature. That's what makes it fun.", "grade >= normal && grade < good", "", ""),
    # 아일리 반응 — bad (d1a_react_bad_*; 구 규칙상 도달 불가 — CONFLICTS 참조)
    ("d2_aili_craft", 37, "say", "aili", "fail", "……이쁜아.", "......Cutie.", "grade < normal", "", "판정 분기: bad(구 규칙상 도달 불가)"),
    ("d2_aili_craft", 38, "say", "luna", "default", "네.", "Yes.", "grade < normal", "", ""),
    ("d2_aili_craft", 39, "say", "aili", "default", "아냐, 아냐. 오늘이 처음이니까 그럴 수 있지.", "No, no. It's your first day — these things happen.", "grade < normal", "", ""),
    ("d2_aili_craft", 40, "say", "aili", "fail", "하지만 다음번에도 이렇게 만들어주면 나도 화낼 거라고.", "But serve me this again next time, and I will get angry.", "grade < normal", "", ""),
    ("d2_aili_craft", 41, "say", "luna", "default", "죄송합니다.", "My apologies.", "grade < normal", "", ""),
    ("d2_aili_craft", 42, "say", "aili", "default", "괜찮아.\n처음부터 잘하면 그것도 좀 무섭지.", "It's fine.\nBeing perfect from day one would be a little scary anyway.", "grade < normal", "", ""),
    # 합류 — 부비의 한 잔 (d1a_after_001~x6)
    ("d2_aili_craft", 43, "say", "bubi", "default", "먀옹.", "Meow.", "", "", "전 판정 합류 지점"),
    ("d2_aili_craft", 44, "say", "aili", "default", "오호.\n부비도 한 잔 마시고 싶은가 본데.", "Oho.\nLooks like Bubi wants a drink too.", "", "", ""),
    ("d2_aili_craft", 45, "say", "luna", "default", "고양이가 원래 술을 마시는 생물이었습니까?", "Are cats creatures that drink alcohol?", "", "", ""),
    ("d2_aili_craft", 46, "say", "aili", "default", "몰라?\n부비는 가끔 마시던데 별문제 없어 보였어.", "You didn't know?\nBubi drinks now and then. Seemed fine to me.", "", "", ""),
    ("d2_aili_craft", 47, "say", "bubi", "default", "먀옹.", "Meow.", "", "", ""),
    ("d2_aili_craft", 48, "say", "aili", "default", "봐봐. 문제없다고 하잖아.\n한 잔 만들어서 줘봐.", "See? She says no problem.\nGo on, make her one.", "", "", ""),
    ("d2_aili_craft", 49, "say", "luna", "default", "(고양이가 좋아하는 칵테일… 그런 게 있는 건가?)", "(A cocktail cats enjoy... does such a thing exist?)", "", "", "독백"),
    ("d2_aili_craft", 50, "order", "bubi", "exact:kahlua_milk", "(고양이가 술을 마실 수 있었나?)", "(Could cats even drink alcohol?)", "", "", "day1_bubi_order1. kahlua_milk는 신 해금표 day6, order 대사는 루나 독백 성격 — CONFLICTS 참조"),
    ("d2_aili_craft", 51, "craft", "", "order", "", "", "", "", ""),
    ("d2_aili_craft", 52, "serve", "bubi", "", "", "", "", "", ""),
    # 부비 반응 — perfect (d1b_react_perfect_*)
    ("d2_aili_craft", 53, "say", "bubi", "default", "미야아옹.", "Meooow.", "grade >= perfect", "", "판정 분기: perfect"),
    ("d2_aili_craft", 54, "say", "luna", "default", "혹시 이건 무슨 반응입니까?", "What sort of reaction is this?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 55, "say", "aili", "success", "좋아하는 것 같은데?", "I'd say she likes it.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 56, "say", "luna", "default", "어떻게 아는 거죠?", "How can you tell?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 57, "say", "aili", "default", "딱히 네 얼굴에 스크래치를 내거나, 잔을 던지는 것도 아니잖아.", "Well, she's not scratching your face or throwing the glass, is she?", "grade >= perfect", "", ""),
    ("d2_aili_craft", 58, "say", "luna", "default", "원래 사나운 성격이었나 보네요.", "So she is fierce by nature.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 59, "say", "bubi", "default", "먀옹.", "Meow.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 60, "say", "aili", "default", "실력이 꽤 괜찮나 보네.\n부비까지 만족시키다니.", "Your skills must be decent.\nSatisfying even Bubi, of all customers.", "grade >= perfect", "", ""),
    ("d2_aili_craft", 61, "say", "luna", "default", "만족한 게 맞다면 다행이네요.", "If she is indeed satisfied, I am relieved.", "grade >= perfect", "", ""),
    # 부비 반응 — good (d1b_react_good_*)
    ("d2_aili_craft", 62, "say", "bubi", "default", "먀옹.", "Meow.", "grade >= good && grade < perfect", "", "판정 분기: good"),
    ("d2_aili_craft", 63, "say", "luna", "default", "반응이 짧아졌습니다.", "The reaction has gotten shorter.", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 64, "say", "aili", "default", "싫어하는 건 아닌 것 같은데?", "Doesn't look like she hates it?", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 65, "say", "luna", "default", "좋아하는 것도 아닌 것 같습니다.", "It does not look like she loves it either.", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 66, "say", "aili", "default", "부비한테 그 정도면 성공이지.", "Coming from Bubi, that counts as a success.", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 67, "say", "luna", "default", "다행이네요.", "That is a relief.", "grade >= good && grade < perfect", "", ""),
    ("d2_aili_craft", 68, "effect", "", "", "", "", "grade >= good", "flag.bubi_affinity_high = true", "원 d1b_bubi_flag_set(set_flag) — good 이상에서만"),
    # 부비 반응 — bad (d1b_react_bad_* : 컷씬 + 부비 퇴장)
    ("d2_aili_craft", 69, "timeline", "", "day1_bubi_drink_reaction", "", "", "grade < good", "", "판정 분기: bad. 컷씬 id 확인 필요"),
    ("d2_aili_craft", 70, "exit", "bubi", "", "", "", "grade < good", "", "원 d1b_react_bad_001. fade_out 0.5s"),
    ("d2_aili_craft", 71, "say", "aili", "default", "별로였나 본데.", "Guess she didn't care for it.", "grade < good", "", ""),
    ("d2_aili_craft", 72, "say", "luna", "default", "정말로 술을 좋아하는 겁니까?", "Does she truly like alcohol?", "grade < good", "", ""),
    ("d2_aili_craft", 73, "say", "aili", "default", "아마도? 듣기론 한 가지 술밖에 안 먹는 걸로 기억해.", "Probably? From what I heard, she only drinks one particular kind.", "grade < good", "", "부비 취향 떡밥"),
    ("d2_aili_craft", 74, "say", "luna", "default", "음… 기억하겠습니다.", "Hm... I will remember that.", "grade < good", "", ""),
    # 합류 — 아일리 퇴장 (d1b_after_001 / d1b_after_nobubi_001 동일 텍스트 병합)
    ("d2_aili_craft", 75, "say", "aili", "default", "오케이. 그럼 먼저 일어나 볼게.", "Okay. I'll head out first, then.", "", "", "양 갈래 공통(병합)"),
    ("d2_aili_craft", 76, "say", "luna", "default", "벌써 가시나요?", "Leaving already?", "", "", ""),
    ("d2_aili_craft", 77, "say", "aili", "default", "영감이 말했던 약속 시간이 끝났거든.\n이제 다시 내 일하러 가야지.", "The old man's little time-out is over.\nBack to my own work now.", "", "", ""),
    ("d2_aili_craft", 78, "say", "luna", "default", "안녕히 가세요.", "Take care.", "", "", ""),
    ("d2_aili_craft", 79, "say", "aili", "default", "그래. 나중에 보자, 이쁜이.", "Sure. See you around, cutie.", "", "", ""),
    ("d2_aili_craft", 80, "exit", "aili", "", "", "", "", "", "fade_out 0.5s"),
    # 부비 잔류 시에만 (d1b_after_001_x6~x9)
    ("d2_aili_craft", 81, "say", "luna", "default", "음… 이쁜이가 무슨 의미인지 다음에 물어봐야겠다.", "Hm... I should ask what 'cutie' means next time.", "flag.bubi_affinity_high", "", "부비 잔류 루트만"),
    ("d2_aili_craft", 82, "say", "bubi", "default", "먀옹.", "Meow.", "flag.bubi_affinity_high", "", ""),
    ("d2_aili_craft", 83, "say", "luna", "default", "당신이랑 저만 남았네요.\n고양이 말은 아직 이해하지 못하는데.", "It is just you and me now.\nI do not yet understand cat language.", "flag.bubi_affinity_high", "", ""),
    ("d2_aili_craft", 84, "say", "bubi", "default", "먀옹.", "Meow.", "flag.bubi_affinity_high", "", ""),

    # ---------- d2_close : 크리스 교대 (d1end_*, condition_branch → flag 게이트 병합) ----------
    ("d2_close", 1,  "enter", "chris", "R", "", "", "", "", "원 d1end_001. silhouette_reveal 1.0s"),
    ("d2_close", 2,  "say", "chris", "default", "루나.\n이제 슬슬 교대하자고.", "Luna.\nTime to switch shifts.", "", "", "양 갈래 공통 첫 대사(병합)"),
    ("d2_close", 3,  "say", "luna", "default", "네, 보스.\n그런데 아직 앞에 손님이 있습니다.", "Yes, Boss.\nHowever, there is still a customer at the counter.", "flag.bubi_affinity_high", "", "부비 잔류 루트(d1end_bubi_*)"),
    ("d2_close", 4,  "say", "chris", "default", "뭐야.\n부비도 있었네.", "What the.\nBubi's here too.", "flag.bubi_affinity_high", "", ""),
    ("d2_close", 5,  "say", "bubi", "default", "먀옹.", "Meow.", "flag.bubi_affinity_high", "", ""),
    ("d2_close", 6,  "say", "chris", "default", "부비는 내가 돌봐줄 테니까 먼저 들어가 봐.", "I'll look after Bubi. You head on home.", "flag.bubi_affinity_high", "", ""),
    ("d2_close", 7,  "say", "luna", "default", "네, 보스.", "Yes, Boss.", "!flag.bubi_affinity_high", "", "일반 루트(d1end_normal_*)"),
    ("d2_close", 8,  "say", "chris", "default", "수고했어. 먼저 들어가 봐.", "Good work. You head on home.", "!flag.bubi_affinity_high", "", ""),
    ("d2_close", 9,  "say", "luna", "default", "알겠습니다.", "Understood.", "", "", "이하 양 갈래 공통(병합)"),
    ("d2_close", 10, "say", "chris", "default", "그래도 첫날치고는 잘했나 보네.", "Seems you did well, for a first day.", "", "", ""),
    ("d2_close", 11, "say", "luna", "default", "잘했다는 걸 어떻게 아는 건가요?", "How do you know I did well?", "", "", ""),
    ("d2_close", 12, "say", "chris", "default", "누가 소리 지르고 뭔갈 집어던지지는 않았잖아?\n그럼 잘한 거지.", "Nobody screamed or threw anything, right?\nThen you did well.", "", "", ""),
    ("d2_close", 13, "say", "luna", "default", "아하… 확인했습니다.", "Ah... confirmed.", "", "", ""),
    ("d2_close", 14, "say", "chris", "default", "그래. 딴 길로 새지 말고 바로 들어가.", "Right. No detours — go straight home.", "", "", ""),
    ("d2_close", 15, "say", "luna", "default", "네, 보스.", "Yes, Boss.", "", "", ""),
    ("d2_close", 16, "end_part", "", "", "", "", "", "", "원 day_end 트리거"),
]

# CHOICE_COLS = ["choice_id","seq","text_ko","text_en","when","effects","goto","note"]
CHOICES = [
    ("ch_d2_aili_lady", 1, "섹시한 레이디가 뭔가요?", "What is a 'sexy lady'?", "", "", "d2_aili_lady_q", "질문 분기 — manual 씬 재생 후 다음 auto 씬(d2_aili_craft)으로 합류"),
    ("ch_d2_aili_lady", 2, "주문받았습니다.", "Order received.", "", "", "", "그대로 진행 — 다음 auto 씬(d2_aili_craft)으로 바로 합류"),
]
