# 구 day2.json → 새 day3 (바 2부) 변환
# 원본: Assets/StreamingAssets/day2.json (264노드, 단일 그래프 씬 "day2_intro") + day2_crafts.json (제조 이벤트 5종)
# 새 규칙: day=3, phase="bar", 씬 id "d3_" 접두 (기존 가안 d3_aili_bubi/d3_samho/d3_cameo_port 회피)

CONFLICTS = [
    "[주문 매핑] day2_samho_order1은 '추천 주문'으로 match_values에 cosmopolitan/dry_martini/gin_fizz/kahlua_milk 4종을 모두 허용하고 칵테일별 반응 대사가 갈림 — 새 DSL의 exact: 주문으로는 '4종 중 아무거나' 표현 불가. 원본 연출 의도(코스모폴리탄이 대표 반응)에 따라 exact:cosmopolitan으로 고정하고 코스모폴리탄 반응만 grade 게이트로 이식. 미이식 반응 대사: d2sm1_dm_*(드라이마티니), d2sm1_gin_*(진피즈), d2sm1_kahlua_*(깔루아밀크) 계열 전부.",
    "[해금일 충돌] 코스모폴리탄(day5 해금)·드라이마티니(day4)·깔루아밀크(day6)가 새 day3 대본에 등장 — 해금일을 앞당기거나 주문 칵테일 교체 필요. 진피즈만 안전.",
    "[비선형 next 24개 처리] (a) 제조 판정 분기: perfect/good/fail 반응 노드들이 합류 노드(d2sm_after1_001, d2sm_after2_001, d2sm_after3_001, d2sm_drunk_flower, d2ai_after_001)로 점프 → when 'grade >= perfect' / 'grade >= good && grade < perfect' / 'grade < good' 게이트를 걸어 STEPS에 선형 인라인. (b) miss 재제조 루프: d2sm1_miss(+d2sm1_retry), d2sm2_react_miss_001, d2sm3_react_miss_001, d2sm_last_react_miss_001, d2ai_react_miss_001 → start_craft 재진입 루프는 새 구조로 표현 불가. exact: 주문이 엔진 단에서 오제조 재시도를 처리한다고 보고 미이식. (c) 선택지 분기: d2sm_choice1_warn/d2sm_serve_more/d2sm_refuse → manual 씬 3개(d3_samho_warn/d3_samho_pour/d3_samho_refuse) + goto, 합류점(d2ai_order)부터 다음 auto 씬 d3_aili_visit로 분리.",
    "[미이식 대사 목록] miss/재제조 계열: d2sm1_miss~x6, d2sm1_retry~x1, d2sm2_react_miss_001~x1, d2sm3_react_miss_001~x1, d2sm_last_react_miss_001~x1, d2ai_react_miss_001~x1. 오제조 재시도 연출이 필요하면 엔진 공용 리액션 프리셋으로 커버 요망.",
    "[원본 정합 이슈] 거절 루트(d2sm_refuse_x4)에서 삼호가 '내일 꽃 보여 줄 테니 기대해!!'라고 말하지만, 꽃 이야기는 만취 루트(d2sm_drunk_flower)에서만 나옴 — 거절 루트에서는 꽃이 언급된 적 없음. 원문 그대로 이식했으니 대본 수정 검토 필요.",
    "[주문대사] order 스텝의 대사는 day2_crafts.json의 order 필드를 사용. 단 day2_samho_order3의 order 텍스트 '마지막 한 잔. (마티니, 만취 상태)'는 메타 주석 포함 — '마지막 한 잔.'만 사용.",
    "[컷씬] start_cutscene 트리거는 원본에 없음. 대신 craft_events의 finish 컷씬 'day1_finish_default'가 5개 주문 전부에 걸려 있음 — 새 엔진 제조 마무리 연출로 대체되는지 컷씬 id 확인 필요.",
    "[씬 분리 예외] 아일리 등장(customer_enter)이 삼호 퇴장 분기 내부(만취/거절 manual 씬)에서 일어나므로, 다음 auto 씬 d3_aili_visit는 아일리가 이미 착석한 상태로 시작 — '등장~퇴장 단위' 원칙의 예외. 분기별 아일리 도입 대사(마가로프 목격담)는 각 manual 씬에 유지.",
    "[수치 미이식] craft reactions의 affinity/skill/tip/payment 수치(예: order1 cosmo_perfect affinity 10, tip 0.2)는 새 구조의 grade 프리셋이 담당한다고 보고 스텝 effects로 이식하지 않음. intoxication 수치(order2 +2, order2_dm/order3 +3)도 대응 DSL 없음 — 취기 연출은 표정(drunk)으로만 반영됨.",
    "[텍스트 태그] <world>/<name> 마크업 태그는 text_ko에 원문 그대로 유지 — 새 엔진 text_styles 지원 여부 확인 필요.",
    "[연출 파라미터 미이식] enter_effect 'silhouette_reveal' / exit_effect 'fade_out' / enter·exit_duration / sfx_mode는 enter/exit 스텝에 대응 필드 없음 — 엔진 기본 연출 사용 가정.",
    "[expression] 원본 expression 값은 default/success/fail/drunk 4종뿐 — 알 수 없는 값 없음. 널은 default로 치환.",
    "[화자] speaker는 luna/chris/samho/aili/system뿐 — 허용 외 캐릭터 없음. system 노드는 전부 text 없는 trigger 전용(sign 화자 미사용).",
]

# SCENES: (id, day, phase, seq, trigger, when, title)
SCENES = [
    ("d3_chris_open",   3, "bar", 1, "auto",   "", "개점 — 크리스의 당부와 외출"),
    ("d3_samho_visit",  3, "bar", 2, "auto",   "", "삼호 첫 술 — 추천 한 잔부터 세 잔까지"),
    ("d3_samho_warn",   3, "bar", 0, "manual", "", "분기 — 취기 경고 (ch_d3_last_call A)"),
    ("d3_samho_pour",   3, "bar", 0, "manual", "", "분기 — 마지막 마티니와 노란 꽃 (death_route)"),
    ("d3_samho_refuse", 3, "bar", 0, "manual", "", "분기 — 서빙 거절 (refused_drink)"),
    ("d3_aili_visit",   3, "bar", 3, "auto",   "", "아일리 — 깔루아 밀크와 안토니오"),
    ("d3_chris_close",  3, "bar", 4, "auto",   "", "크리스 복귀 — 마감"),
]

# STEPS: (scene_id, seq, type, actor, arg, text_ko, text_en, when, effects, note)
STEPS = [
    # ---------- d3_chris_open : 크리스 개점 당부 (day2_intro_x1~x13) ----------
    ("d3_chris_open", 1,  "enter", "chris", "R", "", "", "", "", "원본 silhouette_reveal"),
    ("d3_chris_open", 2,  "say", "chris", "default", "왔군. 오는 길에 별일 있었나?", "You're here. Anything happen on the way in?", "", "", ""),
    ("d3_chris_open", 3,  "say", "luna", "default", "전에 말했던 동물 귀가 달린 사람을 마주쳤습니다.", "I ran into that person with the animal ears I mentioned before.", "", "", ""),
    ("d3_chris_open", 4,  "say", "chris", "default", "흠… 마주쳐서 뭘 했지?", "Hm... and what did you do when you met them?", "", "", ""),
    ("d3_chris_open", 5,  "say", "luna", "default", "몇 번 대화하더니 저를 보고는 제정신이 아닌 것 같다고 했습니다.", "We exchanged a few words, and then they said I didn't seem to be in my right mind.", "", "", ""),
    ("d3_chris_open", 6,  "say", "chris", "default", "흠.. 너는 이 동네 사람 치고는 특이하니까.", "Hm... well, you are odd for someone from this part of town.", "", "", ""),
    ("d3_chris_open", 7,  "say", "chris", "default", "이 동네까지 <world>코라테크</world>가 올 일은 없지만…\n뭐, 조심해서 나쁠 건 없다. 너무 눈에 띄지는 마.", "<world>CoraTech</world> has no business coming this far down...\nStill, caution costs nothing. Don't draw too much attention.", "", "", ""),
    ("d3_chris_open", 8,  "say", "luna", "default", "네, 알겠습니다.", "Yes, understood.", "", "", ""),
    ("d3_chris_open", 9,  "say", "chris", "default", "좋아. 오늘은 내가 잠시 밖에 나갔다 올 거야.\n그동안 바 좀 잘 보고 있어.", "Good. I'll be stepping out for a while today.\nWatch the bar while I'm gone.", "", "", ""),
    ("d3_chris_open", 10, "say", "luna", "default", "네, 보스.", "Yes, Boss.", "", "", ""),
    ("d3_chris_open", 11, "exit", "chris", "", "", "", "", "", "원본 fade_out"),
    ("d3_chris_open", 12, "say", "luna", "default", "음… <world>친구</world>라…", "Hm... a <world>friend</world>, huh...", "", "", "독백"),
    ("d3_chris_open", 13, "say", "luna", "default", "친구는 어떤 걸 뜻하는 건지 모르겠네.\n다시 만나면 물어봐야겠다.", "I don't really know what a friend is supposed to mean.\nI should ask next time we meet.", "", "", "독백"),

    # ---------- d3_samho_visit : 삼호 등장 ~ 3잔 ~ 선택지 (day2_intro_x14 ~ d2sm_after3_001_x45) ----------
    ("d3_samho_visit", 1,  "enter", "samho", "R", "", "", "", "", "원본 silhouette_reveal 1.0s"),
    ("d3_samho_visit", 2,  "say", "samho", "default", "안녕, 나 왔어.", "Hey, I'm here.", "", "", ""),
    ("d3_samho_visit", 3,  "say", "luna", "default", "(바로 만나버렸네.)", "(So we meet again, just like that.)", "", "", "독백"),
    ("d3_samho_visit", 4,  "say", "luna", "default", "진짜 오셨네요.", "You actually came.", "", "", ""),
    ("d3_samho_visit", 5,  "say", "samho", "default", "그럼 내가 온다고 했잖아.\n아무도 없는 걸 보니 내가 첫 손님인가봐.", "I told you I would, didn't I?\nNobody else here — guess that makes me your first customer.", "", "", ""),
    ("d3_samho_visit", 6,  "say", "luna", "default", "주문부터 하실 겁니까?", "Would you like to order first?", "", "", ""),
    ("d3_samho_visit", 7,  "say", "samho", "default", "…크흠, 사실 내가 술집에서 술을 마셔 보는 건\n이번이 처음이란 말이지.", "...Ahem. Truth is, this is my first time\nactually drinking at a bar.", "", "", ""),
    ("d3_samho_visit", 8,  "say", "luna", "default", "제가 경험자로서 말해 주자면, 술은 안 마시는 게 낫습니다.", "Speaking from experience: you're better off not drinking at all.", "", "", ""),
    ("d3_samho_visit", 9,  "say", "samho", "default", "뭐래. 나보다 어려 보이는 게. 어디서 선배인 척하려고.", "Says who? You look younger than me. Don't play the senior with me.", "", "", ""),
    ("d3_samho_visit", 10, "say", "samho", "default", "그래도 이왕 여기까지 왔는데 한 번 마셔 봐야지.", "Still, I came all this way. Might as well try one.", "", "", ""),
    ("d3_samho_visit", 11, "say", "luna", "default", "그럼 어떤 걸 원하시나요?", "Then what would you like?", "", "", ""),
    ("d3_samho_visit", 12, "say", "samho", "default", "네가 <name>추천</name>하는 걸로 하나 만들어 줘.", "Make me whatever you'd <name>recommend</name>.", "", "", ""),
    ("d3_samho_visit", 13, "say", "luna", "default", "(흠.. 처음 마시는 술이니 부담 없는 걸로 줘볼까.)", "(Hm... his first drink ever. Something easy, then.)", "", "", "독백"),
    ("d3_samho_visit", 14, "order", "samho", "exact:cosmopolitan", "너의 추천에 맡길게.", "I'll leave it to your recommendation.", "", "", "원본은 4종 자유 추천(cosmo/dm/gin/kahlua) — CONFLICTS 참조. 주문대사는 crafts json order 필드"),
    ("d3_samho_visit", 15, "craft", "", "order", "", "", "", "", "day2_samho_order1"),
    ("d3_samho_visit", 16, "serve", "samho", "", "", "", "", "", ""),
    ("d3_samho_visit", 17, "say", "samho", "success", "오호… 이건 뭐야?", "Ooh... what's this?", "grade >= perfect", "", "판정 상 (d2sm1_cosmo_perfect)"),
    ("d3_samho_visit", 18, "say", "luna", "default", "코스모폴리탄이라는 술입니다.", "It's called a Cosmopolitan.", "grade >= perfect", "", ""),
    ("d3_samho_visit", 19, "say", "samho", "success", "맛있는데?\n너… 보기보다 실력 있구나?", "This is good.\nYou're... more skilled than you look, huh?", "grade >= perfect", "", ""),
    ("d3_samho_visit", 20, "say", "luna", "default", "감사합니다.", "Thank you.", "grade >= perfect", "", ""),
    ("d3_samho_visit", 21, "say", "samho", "default", "좋아. 인정. 앞으로 자주 와야겠네.", "Alright. Respect. I'll have to come by often.", "grade >= perfect", "", ""),
    ("d3_samho_visit", 22, "say", "samho", "success", "흠… 괜찮은데?", "Hm... not bad at all?", "grade >= good && grade < perfect", "", "판정 중 (d2sm1_cosmo_good)"),
    ("d3_samho_visit", 23, "say", "luna", "default", "코스모폴리탄이라는 술입니다.", "It's called a Cosmopolitan.", "grade >= good && grade < perfect", "", ""),
    ("d3_samho_visit", 24, "say", "samho", "success", "이름도 뭔가 고급지네. 생각보다 괜찮아. 맛있어.", "Even the name sounds classy. Better than I expected. It's good.", "grade >= good && grade < perfect", "", ""),
    ("d3_samho_visit", 25, "say", "luna", "default", "감사합니다.", "Thank you.", "grade >= good && grade < perfect", "", ""),
    ("d3_samho_visit", 26, "say", "samho", "default", "좋아. 인정. 앞으로 자주 와야겠네.", "Alright. Respect. I'll have to come by often.", "grade >= good && grade < perfect", "", ""),
    ("d3_samho_visit", 27, "say", "samho", "fail", "음.. 생긴 건 내 취향이 맞는데 맛이 좀 이상하네..", "Hm... looks exactly like my kind of drink, but it tastes a little off...", "grade < good", "", "판정 하 (d2sm1_cosmo_bad)"),
    ("d3_samho_visit", 28, "say", "luna", "default", "죄송합니다. 제가 실수한 것 같네요.", "I'm sorry. I think I made a mistake.", "grade < good", "", ""),
    ("d3_samho_visit", 29, "say", "samho", "default", "그래도 생각했던 것보다 나쁜 곳은 아닌 것 같네.", "Still, this place isn't as bad as I thought it'd be.", "", "", "합류점 d2sm_after1_001"),
    ("d3_samho_visit", 30, "say", "luna", "default", "술을 마셔 본 적이 없는데 이곳에 온 이유가 있나요?", "You'd never had a drink before — any reason you came here?", "", "", ""),
    ("d3_samho_visit", 31, "say", "samho", "default", "나이 먹은 변태 늙다리들이나 가는 곳인 줄 알았는데.\n너처럼 순하고 어린 애가 일하는 곳이면 한 번쯤 가 볼까 해서.", "I figured bars were for old pervert geezers.\nBut if a soft, young kid like you works here, I thought it was worth a look.", "", "", ""),
    ("d3_samho_visit", 32, "say", "luna", "default", "원래 바는 변태들이 가는 곳입니까?", "Are bars normally places perverts go?", "", "", ""),
    ("d3_samho_visit", 33, "say", "samho", "default", "이 동네에 있는 대부분 술집은 싹 다 매춘업소야.\n술을 즐기는 게 아니라 성욕을 해소하러 가는 곳이다 이거지!", "Most 'bars' around here are all brothels.\nPeople don't go to enjoy a drink — they go to get off, that's what I'm saying!", "", "", ""),
    ("d3_samho_visit", 34, "say", "samho", "default", "그래도 뭐… 이 가게는 확실히 다른 거 같긴 하네.", "But this place... yeah, this place is definitely different.", "", "", ""),
    ("d3_samho_visit", 35, "say", "luna", "default", "다행이네요. 그런 곳에서 일하는 건\n저한텐 어려울 것 같습니다.", "That's a relief. Working at a place like that\nwould be difficult for me.", "", "", ""),
    ("d3_samho_visit", 36, "say", "samho", "default", "하핫! 당연하지. 이 동네가 쓰레기들만 모여 있는 곳이긴 하지만\n여긴 그래도 나름 괜찮은 곳이라고 들었어. 이곳 마스터도 말이지.", "Haha! Obviously. This neighborhood's a dump full of trash,\nbut I heard this place is actually decent. The master here too.", "", "", ""),
    ("d3_samho_visit", 37, "say", "luna", "default", "나쁜 사람은 아닌 것 같습니다.", "He doesn't seem like a bad person.", "", "", ""),
    ("d3_samho_visit", 38, "say", "samho", "default", "나중에 혹시라도 너한테 못되게 굴면 얼마든지 말해.\n내가 특별히 우리 애니멀 갱으로 영입해줄게!", "If he ever treats you badly, just say the word.\nI'll make a special exception and recruit you into our Animal Gang!", "", "", ""),
    ("d3_samho_visit", 39, "say", "luna", "default", "그곳에 들어가면 행복해지나요?", "Would joining make me happy?", "", "", ""),
    ("d3_samho_visit", 40, "say", "samho", "default", "행복? …행복해지는 건 잘 모르겠지만.\n적어도 굶어죽을 일은 없어.", "Happy? ...Can't promise happy.\nBut at least you'd never starve to death.", "", "", ""),
    ("d3_samho_visit", 41, "say", "luna", "default", "갱에서는 무슨 일을 하는데요?", "What kind of work does the gang do?", "", "", ""),
    ("d3_samho_visit", 42, "say", "samho", "default", "음… 배달도 하고, 물건도 찾아오고, 가끔 사람을 지킬 때도 있고, \n처리할 때도 있어. 돈만 주면 다 하지~", "Hm... deliveries, retrievals, sometimes we protect people,\nsometimes we take care of them. Anything, as long as it pays~", "", "", ""),
    ("d3_samho_visit", 43, "say", "luna", "default", "사람을 처리하는 건 죽인다는 걸 의미하는 건가요?", "By 'take care of,' do you mean killing them?", "", "", ""),
    ("d3_samho_visit", 44, "say", "samho", "default", "보통은 그래.", "Usually, yeah.", "", "", ""),
    ("d3_samho_visit", 45, "say", "luna", "default", "이쪽 지역은 살인이 합법인가요?", "Is murder legal in this district?", "", "", ""),
    ("d3_samho_visit", 46, "say", "samho", "default", "아 진짜. 너 어디 외딴 곳에서 살다가 넘어왔어?\n왜 이렇게 질문만 하는 거야. 너 정말 모르는 게 많구나!", "Oh, come on. Did you crawl in from the middle of nowhere?\nWhy is everything a question with you? You really don't know anything!", "", "", ""),
    ("d3_samho_visit", 47, "say", "luna", "default", "불쾌했다면 죄송합니다.", "I'm sorry if that was rude.", "", "", ""),
    ("d3_samho_visit", 48, "say", "samho", "default", "아, 아냐. 죄송할 필요까진 없어.\n뭐, 이쪽 지역이 좀 그런 거야~", "Ah, no, no. Nothing to apologize for.\nIt's just... that's how this district is~", "", "", ""),
    ("d3_samho_visit", 49, "say", "samho", "default", "밑바닥에 있는 사람들이 모여 있어서 다른 지역보다\n유독 살인도 많이 일어나고 돈이면 뭐든 할 수 있는 곳이랄까.", "People from rock bottom all wash up here, so there's\nway more murder than anywhere else, and money buys anything.", "", "", ""),
    ("d3_samho_visit", 50, "say", "luna", "default", "듣던 것보다 위험한 곳이었네요.", "It's more dangerous than I'd heard.", "", "", ""),
    ("d3_samho_visit", 51, "say", "samho", "default", "넌 어디서 왔길래 이런 걸 다 물어보는 거야?", "Where are you even from, asking about all this?", "", "", ""),
    ("d3_samho_visit", 52, "say", "luna", "default", "자세히 말씀드리긴 좀 힘들지만\n말씀하신 대로 정말 외딴 곳에 있다가 왔습니다.", "It's hard to go into detail, but\nlike you said — I really did come from the middle of nowhere.", "", "", ""),
    ("d3_samho_visit", 53, "say", "samho", "default", "그래… 여기 사는 사람 중에 사연 없는 사람은 없더라.\n너도 말 못할 사정이 있겠지.", "Right... nobody living here comes without a story.\nGuess you've got things you can't talk about too.", "", "", ""),
    ("d3_samho_visit", 54, "say", "samho", "default", "어디서 왔는지는 모르지만 조심해.\n이 동네에서는 너같이 순한 애는 살아남기 힘들 거야.", "Don't know where you came from, but be careful.\nA soft kid like you won't survive long in this neighborhood.", "", "", ""),
    ("d3_samho_visit", 55, "say", "luna", "default", "삼호는 괜찮은 건가요?", "Are you okay, Samho?", "", "", ""),
    ("d3_samho_visit", 56, "say", "samho", "default", "나도 뭐… 조심하면서 사는 거지. 에잇, 한 잔 더 줘봐.", "Me? Well... I get by, careful-like. Ah, whatever — give me another.", "", "", ""),
    ("d3_samho_visit", 57, "say", "samho", "default", "이제 슬슬 다른 것도 마셔 보고 싶은데.", "I'm starting to want to try something different.", "", "", ""),
    ("d3_samho_visit", 58, "say", "luna", "default", "이번엔 어떤 걸로 주문하시나요?", "What will it be this time?", "", "", ""),
    ("d3_samho_visit", 59, "say", "samho", "default", "이번엔 좀 탄산이 들어간 청량한 걸로 한 잔 부탁해.", "This time, something fizzy and refreshing, please.", "", "", ""),
    ("d3_samho_visit", 60, "say", "luna", "default", "(탄산이 들어간 청량한 술……)", "(A fizzy, refreshing drink......)", "", "", "독백"),
    ("d3_samho_visit", 61, "order", "samho", "exact:gin_fizz", "탄산이 들어간 청량한 술 한 잔.", "One fizzy, refreshing drink.", "", "", "day2_samho_order2 — 주문대사는 crafts json order 필드"),
    ("d3_samho_visit", 62, "craft", "", "order", "", "", "", "", ""),
    ("d3_samho_visit", 63, "serve", "samho", "", "", "", "", "", ""),
    ("d3_samho_visit", 64, "say", "samho", "success", "크, 시원하다. 이거 좋은데?", "Whew, that's crisp. I like this one!", "grade >= perfect", "", "d2sm2_react_perfect_001"),
    ("d3_samho_visit", 65, "say", "samho", "success", "오, 탄산이 톡 쏘네. 마음에 들어.", "Oh, the fizz really bites. I like it.", "grade >= good && grade < perfect", "", "d2sm2_react_good_001"),
    ("d3_samho_visit", 66, "say", "samho", "default", "음.. 김빠진 느낌인데. 뭐, 그래도 마실 만은 해.", "Hm... tastes a little flat. Well, it's still drinkable.", "grade < good", "", "d2sm2_react_fail_001"),
    ("d3_samho_visit", 67, "say", "luna", "default", "그런데 조심하는 것들이 다른 갱들이나 용병들입니까?", "By the way — the things you're careful about, are they other gangs? Mercenaries?", "", "", "합류점 d2sm_after2_001"),
    ("d3_samho_visit", 68, "say", "samho", "default", "음… 맞아. 요즘 우리 구역 주변에 <world>마가로프</world> 갱 놈들이 우리 갱 사람들을\n자꾸 납치하거나 죽이는 일이 생기고 있거든.", "Hm... yeah. Lately the <world>Magarov</world> gang has been circling our turf,\nkidnapping or killing our people, over and over.", "", "", ""),
    ("d3_samho_visit", 69, "say", "luna", "default", "왜 그런 짓을 하는 거죠?", "Why would they do that?", "", "", ""),
    ("d3_samho_visit", 70, "say", "samho", "default", "나도 그게 잘 이해가 안 돼. 원래 시비가 붙어서 싸우는 경우는 있어도\n이렇게 노골적으로 우리 갱 사람들을 <world>사냥</world>하진 않거든.", "That's what I don't get either. Sure, fights break out over grudges,\nbut nobody used to <world>hunt</world> our people this openly.", "", "", ""),
    ("d3_samho_visit", 71, "say", "luna", "default", "<world>위험한 상황</world>인 것 같습니다.", "That sounds like a <world>dangerous situation</world>.", "", "", ""),
    ("d3_samho_visit", 72, "say", "samho", "default", "뭐 그래도 이런 일이 아예 없던 것도 아니고\n곧 있으면 우리 보스가 해결해준댔어!", "Eh, it's not like this kind of thing never happened before.\nAnd Boss said he'll sort it out soon!", "", "", ""),
    ("d3_samho_visit", 73, "say", "luna", "default", "삼호의 보스도 사람을 잘 지켜 줄 수 있나 보네요.", "Your boss must be good at protecting people, then.", "", "", ""),
    ("d3_samho_visit", 74, "say", "samho", "default", "그래! 우리 보스는 짱짱 세고 카리스마도 넘쳐서 내 롤모델이랄까~\n아마 그 누가 덤벼도 보스가 다 이길걸~", "Yeah! Our boss is crazy strong and oozing charisma — my role model, you could say~\nNo matter who comes at him, Boss would win~", "", "", ""),
    ("d3_samho_visit", 75, "say", "samho", "default", "한 잔 더 만들어 줄래? 보스를 위하여 한 잔 더!", "Make me another? One more — for the Boss!", "", "", ""),
    ("d3_samho_visit", 76, "say", "luna", "default", "벌써요? 이런 속도로 계속 마시면 \n취하는 걸로 알고 있습니다.", "Already? If you keep drinking at this pace,\nI understand you will get drunk.", "", "", ""),
    ("d3_samho_visit", 77, "say", "samho", "default", "음… 취했다는 건 아닌데, 평소보다 좀\n시간이 느려진 것처럼 느껴진달까?", "Hm... I'm not drunk or anything, it's just...\ntime feels a bit slower than usual, maybe?", "", "", ""),
    ("d3_samho_visit", 78, "say", "luna", "default", "그게 취할 때 나타나는 증상이라고 알고 있습니다.", "I understand that is a symptom of being drunk.", "", "", ""),
    ("d3_samho_visit", 79, "say", "samho", "default", "아 몰라몰라, 빨리 한 잔 더 줘.", "Ah, whatever, whatever — hurry up and pour me another.", "", "", ""),
    ("d3_samho_visit", 80, "say", "luna", "default", "…알겠습니다. 주문은 어떤 걸로 하시나요?", "...Very well. What would you like to order?", "", "", ""),
    ("d3_samho_visit", 81, "say", "samho", "default", "이번엔 그 뭐냐, <name>마체테</name>?", "This time, what's it called... a <name>Machete</name>?", "", "", ""),
    ("d3_samho_visit", 82, "say", "luna", "default", "<name>마티니</name>를 말하시는 겁니까?", "Do you mean a <name>Martini</name>?", "", "", ""),
    ("d3_samho_visit", 83, "say", "samho", "default", "그래. 그거 우리 보스가 항상 마시는 거라던데\n나도 한 번 마셔 보고 싶어.", "Yeah, that. I heard it's what our boss always drinks.\nI want to try it too.", "", "", ""),
    ("d3_samho_visit", 84, "say", "luna", "default", "(<name>드라이 마티니</name> 한잔)", "(One <name>Dry Martini</name>.)", "", "", "독백"),
    ("d3_samho_visit", 85, "order", "samho", "exact:dry_martini", "드라이 마티니 한 잔.", "One Dry Martini.", "", "", "day2_samho_order2_dm — 드라이마티니 day4 해금 충돌 주의"),
    ("d3_samho_visit", 86, "craft", "", "order", "", "", "", "", ""),
    ("d3_samho_visit", 87, "serve", "samho", "", "", "", "", "", ""),
    ("d3_samho_visit", 88, "say", "luna", "default", "드라이 마티니 한 잔 나왔습니다.", "One Dry Martini, served.", "grade >= perfect", "", "d2sm3_react_perfect_001"),
    ("d3_samho_visit", 89, "say", "samho", "drunk", "이야아…", "Whoaaa...", "grade >= perfect", "", ""),
    ("d3_samho_visit", 90, "say", "luna", "default", "어떤가요?", "How is it?", "grade >= perfect", "", ""),
    ("d3_samho_visit", 91, "say", "samho", "drunk", "흐흐… 살짝 쓰긴 한데 괜찮네.", "Heh heh... a little bitter, but it's good.", "grade >= perfect", "", ""),
    ("d3_samho_visit", 92, "say", "samho", "drunk", "원래 올리브 같은 건 입에도 안 댔는데에\n꽤나 잘 어울리잖아~ 신기한데에.", "I never touched olives before, y'knooow,\nbut it goes so well with this~ Weird, riiight?", "grade >= perfect", "", ""),
    ("d3_samho_visit", 93, "say", "luna", "default", "드라이 마티니 한 잔 나왔습니다.", "One Dry Martini, served.", "grade >= good && grade < perfect", "", "d2sm3_react_good_001"),
    ("d3_samho_visit", 94, "say", "samho", "drunk", "흐흐… 쓰긴 한데, 보스가 마신다는 그 맛이 이런 건가.", "Heh heh... bitter, but so this is the taste Boss drinks, huh.", "grade >= good && grade < perfect", "", ""),
    ("d3_samho_visit", 95, "say", "samho", "drunk", "으… 이건 좀 너무 쓴데. 그래도 보스가 마시는 거니까 마셔야지.", "Ugh... this one's way too bitter. But it's what Boss drinks, so I'll drink it.", "grade < good", "", "d2sm3_react_fail_001"),
    ("d3_samho_visit", 96, "say", "luna", "default", "말이 더어 느려진 것 같은데요. 취한 걸로 보입니다아.", "Your speech seems sloooower now. You appear to be druuunk.", "", "", "합류점 d2sm_after3_001 — 루나도 말투가 옮음(원문 유지)"),
    ("d3_samho_visit", 97, "say", "samho", "drunk", "너 말투가 더 이상해에.", "Your speech is even weirder~", "", "", ""),
    ("d3_samho_visit", 98, "say", "samho", "drunk", "이런 곳에 자주 오려며언…\n돈을 벌어야 할 이유가 늘어났네에.", "If I wanna come here ofteeen...\nguess that's one more reason to make moneyyy.", "", "", ""),
    ("d3_samho_visit", 99, "say", "luna", "default", "돈을 많이 벌어야 하는 이유가 있나요?\n단순히 돈을 좋아하는 사람처럼 보이진 않습니다.", "Is there a reason you need to make a lot of money?\nYou don't strike me as someone who simply loves money.", "", "", ""),
    ("d3_samho_visit", 100, "say", "samho", "drunk", "으음… 사실은 \n사실은 말이야아……", "Mmm... actually,\nactually, y'seeee......", "", "", ""),
    ("d3_samho_visit", 101, "say", "samho", "drunk", "내가 돌봐 주고 있는 동생들이 있어서…", "There are these little ones I look after...", "", "", ""),
    ("d3_samho_visit", 102, "say", "luna", "default", "동생들을 대신 키워주고 계시는 겁니까?", "You're raising your younger siblings yourself?", "", "", ""),
    ("d3_samho_visit", 103, "say", "samho", "drunk", "맞아.. 소중한 동생들이야. \n무려 일곱 명이나 있다구! 대가족이라고 할 수 있지.", "Yeah... my precious little ones.\nSeven of them, no less! A whole big family, you could say.", "", "", ""),
    ("d3_samho_visit", 104, "say", "luna", "default", "(동생들 이야기가 나오니 취해서 \n흐리멍덩해진 눈이 일순간 또렷해진 것 같다.)", "(At the mention of his siblings, his drink-glazed eyes\nseem to sharpen for a moment.)", "", "", "독백"),
    ("d3_samho_visit", 105, "say", "luna", "default", "그렇게 형제자매가 많은 사람은 처음 봤습니다.", "I've never met anyone with that many siblings.", "", "", ""),
    ("d3_samho_visit", 106, "say", "samho", "drunk", "뭐어, 친동생들은 아니지만 말이지.", "Weeell, they're not blood, mind you.", "", "", ""),
    ("d3_samho_visit", 107, "say", "luna", "default", "음… 어쩌다 그렇게 형제가 생겨난 거죠? \n증식이라도 하는 건가요?", "Hm... how did you end up with so many siblings?\nDo they multiply?", "", "", ""),
    ("d3_samho_visit", 108, "say", "samho", "drunk", "하하, 증식이라니. 너 진짜 웃긴다아.", "Haha, 'multiply'! You're actually hilaaarious.", "", "", ""),
    ("d3_samho_visit", 109, "say", "luna", "default", "일종의 미토콘드리아에 해당하나요? 이해가 되지 않습니다.", "Is this a mitochondria-type situation? I don't understand.", "", "", ""),
    ("d3_samho_visit", 110, "say", "samho", "drunk", "대부분은 길거리에 버려진 애들이지.\n이 동네에서는 흔한 일이야아.", "Most of them were kids left out on the street.\nHappens all the time around heeere.", "", "", ""),
    ("d3_samho_visit", 111, "say", "luna", "default", "그러면 삼호는", "Then were you also—", "", "", ""),
    ("d3_samho_visit", 112, "say", "samho", "drunk", "난 아니야.", "Not me.", "", "", ""),
    ("d3_samho_visit", 113, "say", "samho", "drunk", "…아니였지.", "...Wasn't me. Back then.", "", "", ""),
    ("d3_samho_visit", 114, "say", "samho", "drunk", "………", ".........", "", "", ""),
    ("d3_samho_visit", 115, "say", "samho", "drunk", "…", "...", "", "", ""),
    ("d3_samho_visit", 116, "say", "samho", "drunk", "우리 부모님은 말이지, 참 바보같은 사람들이었어.", "My parents, you know... they were such fools.", "", "", ""),
    ("d3_samho_visit", 117, "say", "samho", "drunk", "그들은 길거리에 나앉은 부랑아들을 도와줄 수 있다고 믿었지.", "They believed they could help the strays out on the streets.", "", "", ""),
    ("d3_samho_visit", 118, "say", "samho", "drunk", "그렇게 거리에 돌아다니던 아이들을 하나 둘 집으로 들여온 거야.", "So they started taking the street kids in, one by one.", "", "", ""),
    ("d3_samho_visit", 119, "say", "samho", "drunk", "그렇게 한 명… 두 명….", "One... then two....", "", "", ""),
    ("d3_samho_visit", 120, "say", "samho", "drunk", "일곱 명이 되던 해에", "And the year it became seven,", "", "", ""),
    ("d3_samho_visit", 121, "say", "samho", "drunk", "집을 나갔어.", "they walked out.", "", "", ""),
    ("d3_samho_visit", 122, "say", "luna", "default", "…", "...", "", "", ""),
    ("d3_samho_visit", 123, "say", "samho", "drunk", "감당이 안 되었나봐.\n뭐 있는 거 없는 거 다 털어서 나갔더라고.\n뭐 그렇게 된 거지~~", "Guess it got to be too much.\nThey cleaned out everything we had and left.\nAnd, well, that's how it went~~", "", "", ""),
    ("d3_samho_visit", 124, "say", "samho", "drunk", "아무튼! 난 내 동생들이 너무 소중해에~~", "Anyway! My little ones are sooo precious to me~~", "", "", ""),
    ("d3_samho_visit", 125, "say", "samho", "drunk", "있지 있지~ 우리 막내가 미술에 재능이 있는 것 같아.\n이거 볼래?", "Hey, hey~ I think our youngest has a real talent for art.\nWanna see?", "", "", ""),
    ("d3_samho_visit", 126, "say", "luna", "default", "(….기괴한 형체의 무언가가 잔뜩 그려져 있다. 도무지 알아볼 수 없다.)", "(....It's covered in grotesque, unidentifiable shapes. I can't make out a thing.)", "", "", "독백"),
    ("d3_samho_visit", 127, "say", "luna", "default", "그건 아닌 것 같은데요.", "I don't think that's the case.", "", "", ""),
    ("d3_samho_visit", 128, "say", "samho", "drunk", "너가 보는 눈이 없어서 그래.\n예술 감각이 떨어지는구나~", "That's 'cause you've got no eye for it.\nNo sense for art at all~", "", "", ""),
    ("d3_samho_visit", 129, "say", "luna", "default", "그런데 이 빨갛고 커다란 그림은 뭔가요?", "By the way, what is this big red one a drawing of?", "", "", ""),
    ("d3_samho_visit", 130, "say", "samho", "drunk", "아 맞다 맞다, 이걸 얘기 안 했구나.", "Oh right, right — I never told you about this!", "", "", ""),
    ("d3_samho_visit", 131, "say", "samho", "default", "이 팔을 보시라. 이것으로 말할 것 같으면 물 흐르듯이 유연한 관절!\n스포츠카를 빼다박은 깔롱한 디자인! 그리고 \n아만타티움도 울고 갈 단단함을 자랑하는", "Behold this arm! I present to you: joints smooth as flowing water!\nA slick design straight off a sports car! And hardness\nthat would make amantatium itself weep —", "", "", ""),
    ("d3_samho_visit", 132, "say", "samho", "default", "네오 닐 암스트롱 겔럭시 a6 with 애플 람보르기니 에디션 아머~!!!!!!", "the Neo Neil Armstrong Galaxy a6 with Apple Lamborghini Edition Armor~!!!!!!", "", "", ""),
    ("d3_samho_visit", 133, "say", "luna", "default", "아…. 네… \"네오 닐 암스트롱 겔럭시 a6 with \n애플 람보르기니 에디션 아머~!!!!!\"는 정말 멋있네요.", "Ah.... yes... the \"Neo Neil Armstrong Galaxy a6 with\nApple Lamborghini Edition Armor~!!!!!\" is truly impressive.", "", "", ""),
    ("d3_samho_visit", 134, "say", "samho", "drunk", "아 반응 뭐야아~ 내가 이 아머를 사기 위해서 얼마나 고생했는지 알아?!!!!", "What's with that reactionnn~ Do you know how hard I worked to buy this armor?!!!!", "", "", ""),
    ("d3_samho_visit", 135, "say", "luna", "default", "제가 잘 알진 못하지만 해당 모듈은 꽤나 비싸 보이는데, \n그런 걸 장만할 정도면 굉장히 유능하시겠는데요.", "I'm no expert, but that module looks quite expensive.\nIf you could afford it, you must be very capable.", "", "", ""),
    ("d3_samho_visit", 136, "say", "samho", "drunk", "우으…. 사실은 나 아직 말단이거든.", "Ugh.... actually, I'm still bottom rung.", "", "", ""),
    ("d3_samho_visit", 137, "say", "samho", "drunk", "그래도 이제 곧 큰 돈을 벌 거야!\n전 재산을 털어서 이 아머를 샀으니까!!\n실적을 쌓아서 갱에서 높은 지위를 얻는 것도 시간문제다~ 이거지.", "But I'm gonna make big money soon!\nI blew my entire savings on this armor!!\nRack up results, climb the gang ladder — it's only a matter of time~ that's the plan.", "", "", ""),
    ("d3_samho_visit", 138, "say", "luna", "default", "그렇게 돈을 벌어서 하고 싶은 것이 있습니까?", "Is there something you want to do with the money you make?", "", "", ""),
    ("d3_samho_visit", 139, "say", "samho", "drunk", "동생들이랑 패밀리 레스토랑에 갈 거야. 들어 본 적 있어?\n동생이 가져온 잡지에서 봤는데 몽글몽글한 함박 스테이크라는 게 있대.\n동생들이랑 배 터지게 먹을 거야!!", "I'm taking my little ones to a family restaurant. Ever heard of those?\nSaw it in a magazine one of them brought home — there's this fluffy thing called a hamburg steak.\nWe're gonna eat till we burst!!", "", "", ""),
    ("d3_samho_visit", 140, "say", "luna", "default", "(패밀리 레스토랑이라.. 현재는 거의 사라진 식당이다.\n교육용 DB에서 확인한 적이 있다.)", "(A family restaurant... a kind of establishment nearly extinct today.\nI've seen them in my educational database.)", "", "", "독백"),
    ("d3_samho_visit", 141, "say", "samho", "drunk", "언젠간 보스의 오른팔로 승진할지도 모르지.\n기분이다! 보스의 오른팔이 될 이 삼호님에게 \n술을 한 잔 더 내오너라아아아!!!!!이왕이면 공짜로~!", "Someday I might even get promoted to Boss's right hand.\nI'm feeling it! Bring another drink for the great Samho,\nfuture right hand of the Boss!!!!! And make it free while you're at it~!", "", "", "선택지 직전 — 삼호 대사(루나 규칙 OK)"),
    ("d3_samho_visit", 142, "choice", "", "ch_d3_last_call", "", "", "", "", "경고 A → d3_samho_warn / 수락 B → d3_samho_pour"),

    # ---------- d3_samho_warn : 취기 경고 분기 (d2sm_choice1_warn ~ _x4) ----------
    ("d3_samho_warn", 1, "say", "luna", "default", "지금 더 마시면 취할 수도 있습니다.", "If you drink any more now, you may get drunk.", "", "", "선택지 대사 에코(원문 유지)"),
    ("d3_samho_warn", 2, "say", "samho", "drunk", "에이, 이거 가지고 뭘 취해. 아직 두 잔밖에 안 마셨어어어.", "Pfft, drunk off this? I've only had two glasses sooo faaar.", "", "", ""),
    ("d3_samho_warn", 3, "say", "luna", "default", "세 잔입니다.", "That was three glasses.", "", "", ""),
    ("d3_samho_warn", 4, "say", "samho", "drunk", "그거나 그거나~", "Same difference~", "", "", ""),
    ("d3_samho_warn", 5, "say", "samho", "drunk", "아무튼 한 잔 정도야 괜찮아~", "Anyway, one more glass is fiiine~", "", "", "선택지 직전 — 삼호 대사(루나 규칙 OK)"),
    ("d3_samho_warn", 6, "choice", "", "ch_d3_cutoff", "", "", "", "", "수락 → d3_samho_pour / 거절 → d3_samho_refuse"),

    # ---------- d3_samho_pour : 마지막 마티니 → 만취 퇴장(death_route) (d2sm_serve_more ~ d2sm_drunk_flower_x21) ----------
    ("d3_samho_pour", 1,  "say", "luna", "default", "알겠습니다. 드리도록 하죠.", "Understood. I'll pour you one.", "", "", ""),
    ("d3_samho_pour", 2,  "say", "samho", "drunk", "그래, 그거야, 루나.", "Yeah, that's the spirit, Luna.", "", "", ""),
    ("d3_samho_pour", 3,  "say", "luna", "default", "주문은 어떤 걸로 하시나요?", "What would you like to order?", "", "", ""),
    ("d3_samho_pour", 4,  "say", "samho", "drunk", "아까 줬던 걸로. <name>드라이 마티니</name>였나?", "The one from before. Was it a <name>Dry Martini</name>?", "", "", ""),
    ("d3_samho_pour", 5,  "say", "luna", "default", "맞습니다. 드디어 기억하시네요.", "Correct. You finally remembered.", "", "", ""),
    ("d3_samho_pour", 6,  "say", "luna", "default", "(마지막 드라이 마티니……)", "(One last Dry Martini......)", "", "", "독백"),
    ("d3_samho_pour", 7,  "order", "samho", "exact:dry_martini", "마지막 한 잔.", "One last glass.", "", "", "day2_samho_order3 — 원문 order 텍스트의 메타 주석 '(마티니, 만취 상태)' 제거"),
    ("d3_samho_pour", 8,  "craft", "", "order", "", "", "", "", ""),
    ("d3_samho_pour", 9,  "serve", "samho", "", "", "", "", "", ""),
    ("d3_samho_pour", 10, "say", "samho", "drunk", "크… 이거지. 너무 맛있는데? 이제 쓴맛도\n별로 안 느껴져. 보스가 왜 이걸 마시는지 알겠네.", "Ahh... that's the one. So good! I can barely taste\nthe bitterness now. I get why Boss drinks this.", "grade >= perfect", "", "d2sm_last_react_perfect_001"),
    ("d3_samho_pour", 11, "say", "samho", "drunk", "크… 이거지. 보스가 마시는 맛이야.", "Ahh... that's the one. The taste of the Boss.", "grade >= good && grade < perfect", "", "d2sm_last_react_good_001"),
    ("d3_samho_pour", 12, "say", "samho", "drunk", "이건.. 내…", "This is... my...", "grade < good", "", "d2sm_last_react_fail_001"),
    ("d3_samho_pour", 13, "say", "luna", "default", "손님은 만취 상태로 보입니다.", "Customer status: heavily intoxicated.", "", "", "합류점 d2sm_drunk_flower"),
    ("d3_samho_pour", 14, "say", "samho", "drunk", "ㅁㅓ슨 소리야. 나 아주 멀!@쩡하다고.", "Whaddya mean. I'm perf!@ctly fine.", "", "", ""),
    ("d3_samho_pour", 15, "say", "samho", "default", "그나저나 루나, 꽃이라는 거 본 적 있어?", "By the way, Luna — you ever seen a flower?", "", "", ""),
    ("d3_samho_pour", 16, "say", "luna", "default", "갑자기 꽃이요? 사진으로 몇 번 본 적 있습니다.", "A flower, out of nowhere? I've seen a few in photographs.", "", "", ""),
    ("d3_samho_pour", 17, "say", "samho", "drunk", "내가 전에 우연히 뒷골목에서 노란색 꽃을 봤는데.\n사진으로 본 거랑 엄청 달라. 냄새도 신기하고.", "I stumbled on a yellow flower in a back alley a while ago.\nTotally different from the photos. Even the smell is amazing.", "", "", ""),
    ("d3_samho_pour", 18, "say", "luna", "default", "오호… 흥미롭네요.", "Oh... how interesting.", "", "", ""),
    ("d3_samho_pour", 19, "say", "samho", "drunk", "그치? 좋아. 오늘 네가 나한테 술도 많이 줬으니까\n이따가 내가 가져올게.", "Right? Alright. You poured me plenty tonight,\nso I'll go grab it for you later.", "", "", ""),
    ("d3_samho_pour", 20, "say", "luna", "default", "그걸 가져올 수 있나요?", "Can it even be brought here?", "", "", ""),
    ("d3_samho_pour", 21, "say", "samho", "drunk", "예전에 우리 보스가 꽃은 가운데 초록색 부분만 안 건드리면\n살아 있을 수 있다고 했어.", "Boss once told me a flower stays alive\nas long as you don't touch the green part in the middle.", "", "", ""),
    ("d3_samho_pour", 22, "say", "luna", "default", "그렇다면 저도 한 번 보고 싶습니다.", "In that case, I'd like to see it too.", "", "", ""),
    ("d3_samho_pour", 23, "enter", "aili", "L", "", "", "", "", "삼호 퇴장 전에 아일리 입장(원본 순서 유지)"),
    ("d3_samho_pour", 24, "say", "aili", "default", "안녕, 예쁜이! 오늘은…", "Hey, gorgeous! Today I'll—", "", "", ""),
    ("d3_samho_pour", 25, "say", "samho", "drunk", "좋아! 마티니도 받았으니 꽃 가지고 다시 올게.\n조금만 기다려, 루나!", "Alright! Got my martini, so I'll be back with the flower.\nJust wait a bit, Luna!", "", "", ""),
    ("d3_samho_pour", 26, "exit", "samho", "", "", "", "", "", "만취 상태로 퇴장"),
    ("d3_samho_pour", 27, "effect", "", "", "", "", "", "flag.samho_death_route = true", "구 set_flag samho_death_route"),
    ("d3_samho_pour", 28, "say", "luna", "default", "…(괜찮은 거 맞겠지?)", "...(He'll be okay, right?)", "", "", "독백"),
    ("d3_samho_pour", 29, "say", "aili", "default", "뭐야, 쟤는 완전히 취했잖아. 저 상태로 내보낸 거야?", "What the— that kid is completely wasted. You let him leave like that?", "", "", ""),
    ("d3_samho_pour", 30, "say", "luna", "default", "…제가 실수한 것 같네요.", "...I believe I made a mistake.", "", "", ""),
    ("d3_samho_pour", 31, "say", "aili", "default", "흠, 조금 걱정이네. 밖에 못 보던 갱 놈들이 있던데.", "Hm, I'm a little worried. There were gang thugs outside I've never seen before.", "", "", ""),
    ("d3_samho_pour", 32, "say", "luna", "default", "어떤 갱이던가요?", "Which gang were they?", "", "", ""),
    ("d3_samho_pour", 33, "say", "aili", "default", "마가로프 놈들 같던데. 이 동네에서 보는 건 처음이야.", "Looked like Magarov boys. First time I've seen them in this neighborhood.", "", "", ""),
    ("d3_samho_pour", 34, "say", "luna", "default", "(…큰일 나는 건 아니겠지?)", "(...Nothing bad is going to happen, right?)", "", "", "독백 — 씬 종료 후 다음 auto 씬 d3_aili_visit로 합류"),

    # ---------- d3_samho_refuse : 서빙 거절 → 멀쩡 퇴장(refused_drink) (d2sm_refuse ~ _x20) ----------
    ("d3_samho_refuse", 1,  "say", "luna", "default", "……", "......", "", "", ""),
    ("d3_samho_refuse", 2,  "say", "samho", "default", "엣, 마시고 싶었는데 아쉽다~", "Aw, I really wanted another~ Too bad~", "", "", ""),
    ("d3_samho_refuse", 3,  "say", "luna", "default", "괜찮으신 건가요?", "Are you all right with that?", "", "", ""),
    ("d3_samho_refuse", 4,  "say", "samho", "default", "너가 그렇다면 그런 거지~\n너 좋은 놈 같으니까 말이야.\n오늘은 뭐 이 정도만 마시지 뭐.", "If you say so, then that's how it is~\nYou seem like a good one, after all.\nGuess this is enough for tonight.", "", "", ""),
    ("d3_samho_refuse", 5,  "say", "samho", "default", "오늘 즐거웠어, 루나.\n내일 꽃 보여 줄 테니 기대해!!", "I had fun tonight, Luna.\nI'll show you the flower tomorrow — look forward to it!!", "", "", "원본 정합 이슈: 이 루트에선 꽃 이야기가 나온 적 없음(CONFLICTS 참조)"),
    ("d3_samho_refuse", 6,  "say", "luna", "default", "그냥 보여 주시는 건가요?", "You'd show me, just like that?", "", "", ""),
    ("d3_samho_refuse", 7,  "say", "samho", "default", "친구 사이인데 그 정도는 해 줘야지.", "That much is a given between friends.", "", "", ""),
    ("d3_samho_refuse", 8,  "say", "luna", "default", "친구…?", "Friends...?", "", "", ""),
    ("d3_samho_refuse", 9,  "say", "samho", "default", "내일 봐, 친구!", "See you tomorrow, friend!", "", "", ""),
    ("d3_samho_refuse", 10, "exit", "samho", "", "", "", "", "", "멀쩡한 상태로 퇴장"),
    ("d3_samho_refuse", 11, "effect", "", "", "", "", "", "flag.samho_refused_drink = true", "구 set_flag samho_refused_drink"),
    ("d3_samho_refuse", 12, "say", "luna", "default", "결국 친구에 대한 건 못 들었네.", "In the end, I never got to ask what a friend is.", "", "", "독백"),
    ("d3_samho_refuse", 13, "enter", "aili", "L", "", "", "", "", ""),
    ("d3_samho_refuse", 14, "say", "aili", "default", "안녕, 예쁜이. 나 왔어.", "Hey, gorgeous. I'm here.", "", "", ""),
    ("d3_samho_refuse", 15, "say", "luna", "default", "어서 오세요, 아일리.", "Welcome, Aili.", "", "", ""),
    ("d3_samho_refuse", 16, "say", "aili", "default", "밖에 웬 못 보던 갱 놈들이 있던데.", "There were gang thugs outside I've never seen before.", "", "", ""),
    ("d3_samho_refuse", 17, "say", "luna", "default", "어떤 갱이던가요?", "Which gang were they?", "", "", ""),
    ("d3_samho_refuse", 18, "say", "aili", "default", "옷 뒤에 무슨 '마카로니'라고 쓰여 있던데?", "Their jackets said something like 'Macaroni' on the back?", "", "", ""),
    ("d3_samho_refuse", 19, "say", "luna", "default", "혹시 <world>마가로프</world>인가요?", "Do you mean <world>Magarov</world>?", "", "", ""),
    ("d3_samho_refuse", 20, "say", "aili", "default", "아, 맞아. 그거였어.", "Ah, right. That was it.", "", "", ""),
    ("d3_samho_refuse", 21, "say", "luna", "default", "(…뭔 일 있는 건 아니겠지?)", "(...I hope nothing's going on out there.)", "", "", "독백 — 씬 종료 후 다음 auto 씬 d3_aili_visit로 합류"),

    # ---------- d3_aili_visit : 깔루아 밀크 + 안토니오 (d2ai_order ~ d2ai_after_001_x9) ----------
    # 주의: 아일리는 직전 분기 씬(d3_samho_pour/d3_samho_refuse)에서 이미 입장한 상태
    ("d3_aili_visit", 1,  "say", "aili", "default", "좋아, 루나. 오늘은 <name>깔루아밀크</name> 한 잔 줘.", "Alright, Luna. Tonight, give me a <name>Kahlua Milk</name>.", "", "", ""),
    ("d3_aili_visit", 2,  "say", "luna", "default", "네, 알겠습니다.", "Yes, understood.", "", "", ""),
    ("d3_aili_visit", 3,  "say", "luna", "default", "(<name>깔루아 밀크</name> 한잔)", "(One <name>Kahlua Milk</name>.)", "", "", "독백"),
    ("d3_aili_visit", 4,  "order", "aili", "exact:kahlua_milk", "깔루아 밀크 한 잔.", "One Kahlua Milk.", "", "", "day2_aili_order1 — 깔루아밀크 day6 해금 충돌 주의"),
    ("d3_aili_visit", 5,  "craft", "", "order", "", "", "", "", ""),
    ("d3_aili_visit", 6,  "serve", "aili", "", "", "", "", "", ""),
    ("d3_aili_visit", 7,  "say", "aili", "success", "크… 이거지. 오랜만에 이 우유를 마시고 싶었어.", "Ahh... that's the stuff. I've been craving this milk for ages.", "grade >= perfect", "", "d2ai_react_perfect_001"),
    ("d3_aili_visit", 8,  "say", "aili", "success", "크… 이거지.", "Ahh... that's the stuff.", "grade < perfect", "", "d2ai_react_good_001 — 원본은 fail도 good 반응"),
    ("d3_aili_visit", 9,  "say", "luna", "default", "우유를 좋아하시나요?", "Do you like milk?", "", "", "합류점 d2ai_after_001"),
    ("d3_aili_visit", 10, "say", "aili", "success", "당연하지. 이 주변에서 신선한 우유를 마실 수 있는 곳이\n여기밖에 없다니까? 요즘 우유가 얼마나 귀하고 비싼데.", "Obviously. This is the only place around\nwhere you can get fresh milk, you know? Milk's so rare and pricey these days.", "", "", ""),
    ("d3_aili_visit", 11, "say", "aili", "default", "근데 여기는 재료를 계속 보내 주는 사람이 있다고 들었어.\n이름이 안토니오였나? 가끔 손님으로 온다던데.", "But I heard someone keeps this place supplied.\nAntonio, was it? They say he drops by as a customer sometimes.", "", "", ""),
    ("d3_aili_visit", 12, "say", "luna", "default", "안토니오. 기억해 두겠습니다.", "Antonio. I'll remember that.", "", "", ""),
    ("d3_aili_visit", 13, "say", "aili", "default", "그래. 그럼 난 간당~", "Good. Well, I'm off~", "", "", ""),
    ("d3_aili_visit", 14, "say", "luna", "default", "술을 마시고 바로 일을 해도 되나요? 효율이 떨어질 것 같습니다.", "Is it all right to work right after drinking? Your efficiency will suffer.", "", "", ""),
    ("d3_aili_visit", 15, "say", "aili", "default", "술 마시고 일을 하는 게 진짜 즐거움인데.\n그래, 오늘은 다리 파츠를 팔에다 붙여 달라고 요청하는\n멍청이들이 있어서.", "Working with a drink in you is the real joy.\nAnd yeah — tonight I've got idiots asking me\nto graft leg parts onto their arms.", "", "", ""),
    ("d3_aili_visit", 16, "say", "luna", "default", "쉽지 않겠네요.", "That won't be easy.", "", "", ""),
    ("d3_aili_visit", 17, "say", "aili", "default", "다 그렇지 뭐.\n암튼 가 볼게, 루나. 안녕안녕.", "That's how it always is.\nAnyway, I'm off, Luna. Bye-bye.", "", "", ""),
    ("d3_aili_visit", 18, "exit", "aili", "", "", "", "", "", ""),

    # ---------- d3_chris_close : 크리스 복귀 + 마감 (d2ai_after_001_x10 ~ x18) ----------
    ("d3_chris_close", 1, "enter", "chris", "R", "", "", "", "", ""),
    ("d3_chris_close", 2, "say", "chris", "default", "오늘따라 바깥이 소란스럽군.", "It's noisy out there tonight.", "", "", "마가로프 복선"),
    ("d3_chris_close", 3, "say", "luna", "default", "어서 오세요, 크리스.", "Welcome back, Chris.", "", "", ""),
    ("d3_chris_close", 4, "say", "chris", "default", "크리스 아니고 보스라고 부르기로 했을 텐데.", "I believe we agreed on 'Boss,' not 'Chris.'", "", "", ""),
    ("d3_chris_close", 5, "say", "luna", "default", "넵, 크리..보스.", "Yes, Chri... Boss.", "", "", ""),
    ("d3_chris_close", 6, "say", "chris", "default", "고생했다. 이제 퇴근해.", "Good work today. Clock out.", "", "", ""),
    ("d3_chris_close", 7, "say", "luna", "default", "넵, 알겠습니다.", "Yes, understood.", "", "", ""),
    ("d3_chris_close", 8, "exit", "chris", "", "", "", "", "", ""),
    ("d3_chris_close", 9, "end_part", "", "", "", "", "", "", "구 day_end 트리거"),
]

# CHOICES: (choice_id, seq, text_ko, text_en, when, effects, goto, note)
CHOICES = [
    ("ch_d3_last_call", 1, "지금 더 마시면 취할 수도 있습니다.", "If you drink more now, you may get drunk.", "", "", "d3_samho_warn", "경고 루트 — 2차 선택지로"),
    ("ch_d3_last_call", 2, "네, 알겠습니다.", "Yes, understood.", "", "", "d3_samho_pour", "바로 서빙 → 만취 퇴장(death_route)"),
    ("ch_d3_cutoff",    1, "음… 알겠습니다.", "Well... all right.", "", "", "d3_samho_pour", "결국 서빙 → 만취 퇴장(death_route)"),
    ("ch_d3_cutoff",    2, "안 됩니다. 더는 드릴 수 없습니다.", "No. I can't serve you any more.", "", "", "d3_samho_refuse", "서빙 거절 → 멀쩡 퇴장(refused_drink)"),
]
